/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  AvailableScheduleResponse,
  ErrorResponse,
  ScheduleSeatStatusResponse,
  SseEmitter
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 특정 회차의 상세 정보를 조회합니다.

- 등급별 가격 및 잔여석 수 포함

**권한: 누구나**
 * @summary 단일 회차 조회
 */
export type getScheduleResponse200 = {
  data: AvailableScheduleResponse
  status: 200
}

export type getScheduleResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getScheduleResponseSuccess = (getScheduleResponse200) & {
  headers: Headers;
};
export type getScheduleResponseError = (getScheduleResponse404) & {
  headers: Headers;
};

export type getScheduleResponse = (getScheduleResponseSuccess | getScheduleResponseError)

export const getGetScheduleUrl = (scheduleId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/schedules/${scheduleId}`
}

export const getSchedule = async (scheduleId: number, options?: RequestInit): Promise<getScheduleResponse> => {
  
  return orvalFetch<getScheduleResponse>(getGetScheduleUrl(scheduleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 
            SSE(Server-Sent Events)를 통해 좌석 상태 변경을 실시간으로 수신합니다.

            **이벤트 타입:**
            - `connect`: 연결 성공
            - `seat-update`: 좌석 상태 변경 (OCCUPIED/RELEASED/CONFIRMED)
            - `heartbeat`: 연결 유지 (45초마다)

            **권한: 누구나**
        
 * @summary 좌석 상태 실시간 구독 (SSE)
 */
export type subscribeSeatEventsResponse200 = {
  data: SseEmitter
  status: 200
}
    
export type subscribeSeatEventsResponseSuccess = (subscribeSeatEventsResponse200) & {
  headers: Headers;
};
;

export type subscribeSeatEventsResponse = (subscribeSeatEventsResponseSuccess)

export const getSubscribeSeatEventsUrl = (scheduleId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/schedules/${scheduleId}/seats/stream`
}

export const subscribeSeatEvents = async (scheduleId: number, options?: RequestInit): Promise<subscribeSeatEventsResponse> => {
  
  return orvalFetch<subscribeSeatEventsResponse>(getSubscribeSeatEventsUrl(scheduleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 특정 회차의 좌석 상태 목록을 조회합니다. PENDING(점유 중), RESERVED(예약 완료) 상태인 좌석만 반환합니다.

**권한: 누구나**
 * @summary 회차별 좌석 상태 조회
 */
export type getSeatStatusResponse200 = {
  data: ScheduleSeatStatusResponse
  status: 200
}

export type getSeatStatusResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getSeatStatusResponseSuccess = (getSeatStatusResponse200) & {
  headers: Headers;
};
export type getSeatStatusResponseError = (getSeatStatusResponse404) & {
  headers: Headers;
};

export type getSeatStatusResponse = (getSeatStatusResponseSuccess | getSeatStatusResponseError)

export const getGetSeatStatusUrl = (scheduleId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/schedules/${scheduleId}/seat-status`
}

export const getSeatStatus = async (scheduleId: number, options?: RequestInit): Promise<getSeatStatusResponse> => {
  
  return orvalFetch<getSeatStatusResponse>(getGetSeatStatusUrl(scheduleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


