/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  BookingDetailResponse,
  BookingHistoryResponse,
  BookingResponse,
  BookingTimeResponse,
  ErrorResponse,
  ReleaseBookingRequest,
  StartBookingRequest
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 결제를 완료하고 예매를 최종 확정합니다.

**권한: USER**

**[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
 * @summary 예매 확정
 */
export type confirmBookingResponse200 = {
  data: BookingResponse
  status: 200
}

export type confirmBookingResponse404 = {
  data: ErrorResponse
  status: 404
}

export type confirmBookingResponse410 = {
  data: ErrorResponse
  status: 410
}
    
export type confirmBookingResponseSuccess = (confirmBookingResponse200) & {
  headers: Headers;
};
export type confirmBookingResponseError = (confirmBookingResponse404 | confirmBookingResponse410) & {
  headers: Headers;
};

export type confirmBookingResponse = (confirmBookingResponseSuccess | confirmBookingResponseError)

export const getConfirmBookingUrl = (bookingId: string,) => {


  

  return `https://ticket-api.devhong.cc/api/bookings/${bookingId}/confirm`
}

export const confirmBooking = async (bookingId: string, options?: RequestInit): Promise<confirmBookingResponse> => {
  
  return orvalFetch<confirmBookingResponse>(getConfirmBookingUrl(bookingId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * 
            결제 진입 시점에 선택한 좌석들을 일괄 점유합니다.

            - 최대 4석까지 선택 가능
            - 점유 시간은 2분 (만료 시 자동 해제)
            - 기존 진행 중인 예매가 있으면 자동 취소 후 새 예매 생성
            - 동시에 같은 좌석을 선택한 경우 먼저 요청한 사용자만 성공 (409 Conflict)

            **권한: USER**

            **[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
        
 * @summary 예매 시작 (좌석 일괄 점유)
 */
export type startBookingResponse200 = {
  data: BookingResponse
  status: 200
}

export type startBookingResponse404 = {
  data: ErrorResponse
  status: 404
}

export type startBookingResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type startBookingResponseSuccess = (startBookingResponse200) & {
  headers: Headers;
};
export type startBookingResponseError = (startBookingResponse404 | startBookingResponse409) & {
  headers: Headers;
};

export type startBookingResponse = (startBookingResponseSuccess | startBookingResponseError)

export const getStartBookingUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/bookings/start`
}

export const startBooking = async (startBookingRequest: StartBookingRequest, options?: RequestInit): Promise<startBookingResponse> => {
  
  return orvalFetch<startBookingResponse>(getStartBookingUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      startBookingRequest,)
  }
);}


/**
 * 
            페이지 unload 시 navigator.sendBeacon을 통한 예매 해제용 POST 엔드포인트입니다.

            - sendBeacon은 POST 방식만 지원하므로 별도 엔드포인트 제공
            - 기능은 DELETE /api/bookings/{bookingId}와 동일하게 동작합니다.
            - 결제 전(PENDING) 상태의 예매는 이력에 남지 않도록 즉시 해제합니다.

            **권한: USER**

            **[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
        
 * @summary 예매 해제 (POST 방식)
 */
export type releaseBookingResponse200 = {
  data: BookingResponse
  status: 200
}

export type releaseBookingResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type releaseBookingResponseSuccess = (releaseBookingResponse200) & {
  headers: Headers;
};
export type releaseBookingResponseError = (releaseBookingResponse404) & {
  headers: Headers;
};

export type releaseBookingResponse = (releaseBookingResponseSuccess | releaseBookingResponseError)

export const getReleaseBookingUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/bookings/released`
}

export const releaseBooking = async (releaseBookingRequest: ReleaseBookingRequest, options?: RequestInit): Promise<releaseBookingResponse> => {
  
  return orvalFetch<releaseBookingResponse>(getReleaseBookingUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      releaseBookingRequest,)
  }
);}


/**
 * 특정 예매 건의 상세 내역과 결제 정보를 조회합니다.

**권한: USER**
 * @summary 내 예매 상세 조회
 */
export type getBookingDetailResponse200 = {
  data: BookingDetailResponse
  status: 200
}

export type getBookingDetailResponse404 = {
  data: BookingDetailResponse
  status: 404
}
    
export type getBookingDetailResponseSuccess = (getBookingDetailResponse200) & {
  headers: Headers;
};
export type getBookingDetailResponseError = (getBookingDetailResponse404) & {
  headers: Headers;
};

export type getBookingDetailResponse = (getBookingDetailResponseSuccess | getBookingDetailResponseError)

export const getGetBookingDetailUrl = (bookingId: string,) => {


  

  return `https://ticket-api.devhong.cc/api/bookings/${bookingId}`
}

export const getBookingDetail = async (bookingId: string, options?: RequestInit): Promise<getBookingDetailResponse> => {
  
  return orvalFetch<getBookingDetailResponse>(getGetBookingDetailUrl(bookingId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 
        진행 중인 예매 건 전체를 취소하거나 점유를 해제합니다.

        - 결제 전(PENDING): 점유를 즉시 해제하며, 사용자의 예매 이력에 남지 않습니다. (RELEASED 상태)
        - 결제 후(CONFIRMED): 결제 환불을 진행하고, 사용자의 예매 이력에 '취소됨'으로 표시됩니다. (CANCELLED 상태)

        **권한: USER**

        **[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
    
 * @summary 예매 취소 (전체)
 */
export type cancelBookingResponse200 = {
  data: BookingResponse
  status: 200
}

export type cancelBookingResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type cancelBookingResponseSuccess = (cancelBookingResponse200) & {
  headers: Headers;
};
export type cancelBookingResponseError = (cancelBookingResponse404) & {
  headers: Headers;
};

export type cancelBookingResponse = (cancelBookingResponseSuccess | cancelBookingResponseError)

export const getCancelBookingUrl = (bookingId: string,) => {


  

  return `https://ticket-api.devhong.cc/api/bookings/${bookingId}`
}

export const cancelBooking = async (bookingId: string, options?: RequestInit): Promise<cancelBookingResponse> => {
  
  return orvalFetch<cancelBookingResponse>(getCancelBookingUrl(bookingId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * 진행 중인 예매의 남은 시간(초)을 조회합니다.

**권한: USER**
 * @summary 예매 남은 시간 조회
 */
export type getRemainingTimeResponse200 = {
  data: BookingTimeResponse
  status: 200
}

export type getRemainingTimeResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getRemainingTimeResponseSuccess = (getRemainingTimeResponse200) & {
  headers: Headers;
};
export type getRemainingTimeResponseError = (getRemainingTimeResponse404) & {
  headers: Headers;
};

export type getRemainingTimeResponse = (getRemainingTimeResponseSuccess | getRemainingTimeResponseError)

export const getGetRemainingTimeUrl = (bookingId: string,) => {


  

  return `https://ticket-api.devhong.cc/api/bookings/${bookingId}/time`
}

export const getRemainingTime = async (bookingId: string, options?: RequestInit): Promise<getRemainingTimeResponse> => {
  
  return orvalFetch<getRemainingTimeResponse>(getGetRemainingTimeUrl(bookingId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 로그인한 사용자의 전체 예매 내역(확정/취소)을 조회합니다.

**권한: USER**
 * @summary 내 예매 내역 조회
 */
export type getMyBookingsResponse200 = {
  data: BookingHistoryResponse[]
  status: 200
}
    
export type getMyBookingsResponseSuccess = (getMyBookingsResponse200) & {
  headers: Headers;
};
;

export type getMyBookingsResponse = (getMyBookingsResponseSuccess)

export const getGetMyBookingsUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/bookings/me`
}

export const getMyBookings = async ( options?: RequestInit): Promise<getMyBookingsResponse> => {
  
  return orvalFetch<getMyBookingsResponse>(getGetMyBookingsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


