/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type {
  BookingResponse,
  BookingTimeResponse,
  ErrorResponse,
  StartBookingRequest
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 결제를 완료하고 예매를 최종 확정합니다.
 * @summary 예매 확정
 */
export type confirmBookingResponse200 = {
  data: BookingResponse
  status: 200
}

export type confirmBookingResponse404 = {
  data: ErrorResponse
  status: 404
}

export type confirmBookingResponse410 = {
  data: ErrorResponse
  status: 410
}
    
export type confirmBookingResponseSuccess = (confirmBookingResponse200) & {
  headers: Headers;
};
export type confirmBookingResponseError = (confirmBookingResponse404 | confirmBookingResponse410) & {
  headers: Headers;
};

export type confirmBookingResponse = (confirmBookingResponseSuccess | confirmBookingResponseError)

export const getConfirmBookingUrl = (bookingId: string,) => {


  

  return `https://ticket-api.devhong.cc/api/bookings/${bookingId}/confirm`
}

export const confirmBooking = async (bookingId: string, options?: RequestInit): Promise<confirmBookingResponse> => {
  
  return orvalFetch<confirmBookingResponse>(getConfirmBookingUrl(bookingId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * 
            결제 진입 시점에 선택한 좌석들을 일괄 점유합니다.

            - 최대 4석까지 선택 가능
            - 점유 시간은 5분 (만료 시 자동 해제)
            - 기존 진행 중인 예매가 있으면 자동 취소 후 새 예매 생성
            - 동시에 같은 좌석을 선택한 경우 먼저 요청한 사용자만 성공 (409 Conflict)
        
 * @summary 예매 시작 (좌석 일괄 점유)
 */
export type startBookingResponse200 = {
  data: BookingResponse
  status: 200
}

export type startBookingResponse404 = {
  data: ErrorResponse
  status: 404
}

export type startBookingResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type startBookingResponseSuccess = (startBookingResponse200) & {
  headers: Headers;
};
export type startBookingResponseError = (startBookingResponse404 | startBookingResponse409) & {
  headers: Headers;
};

export type startBookingResponse = (startBookingResponseSuccess | startBookingResponseError)

export const getStartBookingUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/bookings/start`
}

export const startBooking = async (startBookingRequest: StartBookingRequest, options?: RequestInit): Promise<startBookingResponse> => {
  
  return orvalFetch<startBookingResponse>(getStartBookingUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      startBookingRequest,)
  }
);}


/**
 * 진행 중인 예매의 남은 시간(초)을 조회합니다.
 * @summary 예매 남은 시간 조회
 */
export type getRemainingTimeResponse200 = {
  data: BookingTimeResponse
  status: 200
}

export type getRemainingTimeResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getRemainingTimeResponseSuccess = (getRemainingTimeResponse200) & {
  headers: Headers;
};
export type getRemainingTimeResponseError = (getRemainingTimeResponse404) & {
  headers: Headers;
};

export type getRemainingTimeResponse = (getRemainingTimeResponseSuccess | getRemainingTimeResponseError)

export const getGetRemainingTimeUrl = (bookingId: string,) => {


  

  return `https://ticket-api.devhong.cc/api/bookings/${bookingId}/time`
}

export const getRemainingTime = async (bookingId: string, options?: RequestInit): Promise<getRemainingTimeResponse> => {
  
  return orvalFetch<getRemainingTimeResponse>(getGetRemainingTimeUrl(bookingId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 진행 중인 예매 건 전체를 취소합니다.
 * @summary 예매 취소 (전체)
 */
export type cancelBookingResponse200 = {
  data: BookingResponse
  status: 200
}

export type cancelBookingResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type cancelBookingResponseSuccess = (cancelBookingResponse200) & {
  headers: Headers;
};
export type cancelBookingResponseError = (cancelBookingResponse404) & {
  headers: Headers;
};

export type cancelBookingResponse = (cancelBookingResponseSuccess | cancelBookingResponseError)

export const getCancelBookingUrl = (bookingId: string,) => {


  

  return `https://ticket-api.devhong.cc/api/bookings/${bookingId}`
}

export const cancelBooking = async (bookingId: string, options?: RequestInit): Promise<cancelBookingResponse> => {
  
  return orvalFetch<cancelBookingResponse>(getCancelBookingUrl(bookingId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


