/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  NoticeGroupResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 활성화된 공지사항을 카테고리별로 그룹화하여 조회합니다.

**권한: 누구나**
 * @summary 카테고리별 그룹화된 공지사항 조회
 */
export type getActiveNoticesGroupedResponse200 = {
  data: NoticeGroupResponse[]
  status: 200
}
    
export type getActiveNoticesGroupedResponseSuccess = (getActiveNoticesGroupedResponse200) & {
  headers: Headers;
};
;

export type getActiveNoticesGroupedResponse = (getActiveNoticesGroupedResponseSuccess)

export const getGetActiveNoticesGroupedUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/notices/grouped`
}

export const getActiveNoticesGrouped = async ( options?: RequestInit): Promise<getActiveNoticesGroupedResponse> => {
  
  return orvalFetch<getActiveNoticesGroupedResponse>(getGetActiveNoticesGroupedUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


