/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { AddHomeTagRequestTag } from './addHomeTagRequestTag';

/**
 * 홈 태그 추가 요청 DTO
 */
export interface AddHomeTagRequest {
  /** 추가할 홈 섹션 태그 (예: MUSICAL, WEEKLY_OPEN) */
  tag: AddHomeTagRequestTag;
  /**
   * 해당 태그 내에서의 노출 순서. 입력하지 않으면 마지막 순서로 자동 지정됩니다.
   * @minimum 0
   */
  displayOrder?: number;
}
