/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 관리자 회원가입 요청 DTO
 */
export interface AdminSignupRequest {
  /** 로그인 ID */
  loginId: string;
  /** 이름 */
  name: string;
  /** 비밀번호 */
  password: string;
}
