/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 관리자 정보 응답 DTO
 */
export interface AdminResponse {
  /** 관리자 ID */
  id: number;
  /** 로그인 ID */
  loginId: string;
  /** 이름 */
  name: string;
  /** 생성일시 */
  createdAt?: string;
}
