/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { BookingStatus } from './bookingStatus';
import type { AdminBookingResponsePaymentStatus } from './adminBookingResponsePaymentStatus';

/**
 * 관리자용 예매 내역 상세 응답
 */
export interface AdminBookingResponse {
  /** 예매 ID */
  bookingId: string;
  /** 예매 번호 */
  bookingNumber: string;
  /** 예매자 이메일 */
  userEmail: string;
  /** 예매자 이름 */
  username: string;
  /** 예매자 연락처 */
  phoneNumber?: string;
  status: BookingStatus;
  /** 총 결제 금액 */
  totalPrice: number;
  /** 예매 일시 */
  createdAt: string;
  /** 좌석 정보 요약 */
  seatSummary: string;
  /** 결제 상태 */
  paymentStatus?: AdminBookingResponsePaymentStatus;
  /** 결제 수단 */
  paymentMethod?: string;
  /** 결제/환불 완료 시각 */
  paymentCompletedAt?: string;
}
