/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 관리자 정보 응답 DTO
 */
export interface AdminResponse {
  /** 관리자 ID */
  id: number;
  /** 관리자 로그인 ID */
  loginId: string;
  /** 관리자 이름 */
  name: string;
  /** 관리자 생성일시 */
  createdAt?: string;
}
