/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 할인 유형 (COUPON, POINT, PROMOTION)
 */
export type AppliedDiscountDtoType = typeof AppliedDiscountDtoType[keyof typeof AppliedDiscountDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppliedDiscountDtoType = {
  COUPON: 'COUPON',
  PROMOTION: 'PROMOTION',
  GRADE: 'GRADE',
  POINT: 'POINT',
  WELFARE: 'WELFARE',
  ETC: 'ETC',
} as const;
