/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { AuditLogResponseUserRole } from './auditLogResponseUserRole';
import type { AuditLogResponseAction } from './auditLogResponseAction';
import type { AuditLogResponseCategory } from './auditLogResponseCategory';
import type { AuditLogResponseTargetType } from './auditLogResponseTargetType';

/**
 * 감사 로그 응답
 */
export interface AuditLogResponse {
  /** 로그 ID */
  id: number;
  /** 사용자 ID */
  userId: number;
  /** 사용자 이메일 */
  userEmail?: string;
  /** 사용자 역할 */
  userRole?: AuditLogResponseUserRole;
  /** 액션 */
  action: AuditLogResponseAction;
  /** 액션 설명 */
  actionDescription: string;
  /** 카테고리 */
  category: AuditLogResponseCategory;
  /** 대상 타입 */
  targetType?: AuditLogResponseTargetType;
  /** 대상 ID */
  targetId?: string;
  /** 설명 */
  description?: string;
  /** 요청 경로 */
  requestPath?: string;
  /** HTTP 메서드 */
  requestMethod?: string;
  /** 응답 상태 코드 */
  responseStatus?: number;
  /** 응답 상태 설명 (관리자용) */
  responseStatusDescription?: string;
  /** IP 주소 */
  ipAddress?: string;
  /** 생성 일시 */
  createdAt: string;
}
