/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { PeriodInfo } from './periodInfo';
import type { AuditLogStatsResponseByCategory } from './auditLogStatsResponseByCategory';
import type { ActionCount } from './actionCount';

/**
 * 감사 로그 통계 응답
 */
export interface AuditLogStatsResponse {
  period: PeriodInfo;
  /** 전체 로그 수 */
  totalCount: number;
  /** 카테고리별 통계 */
  byCategory: AuditLogStatsResponseByCategory;
  /** 액션별 통계 (상위 10개) */
  byAction: ActionCount[];
}
