/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 감사 로그 카테고리
 */
export type AuditCategory = typeof AuditCategory[keyof typeof AuditCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditCategory = {
  AUTH: 'AUTH',
  ACCOUNT: 'ACCOUNT',
  BOOKING: 'BOOKING',
  PAYMENT: 'PAYMENT',
  ADMIN: 'ADMIN',
  SEAT: 'SEAT',
} as const;
