/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { AuditLogDetailResponseUserRole } from './auditLogDetailResponseUserRole';
import type { AuditLogDetailResponseAction } from './auditLogDetailResponseAction';
import type { AuditLogDetailResponseCategory } from './auditLogDetailResponseCategory';
import type { AuditLogDetailResponseTargetType } from './auditLogDetailResponseTargetType';

/**
 * 감사 로그 상세 응답 (요청 본문 포함)
 */
export interface AuditLogDetailResponse {
  /** 로그 ID */
  id: number;
  /** 사용자 ID */
  userId: number;
  /** 사용자 이메일 */
  userEmail?: string;
  /** 사용자 역할 */
  userRole?: AuditLogDetailResponseUserRole;
  /** 액션 */
  action: AuditLogDetailResponseAction;
  /** 액션 설명 */
  actionDescription: string;
  /** 카테고리 */
  category: AuditLogDetailResponseCategory;
  /** 대상 타입 */
  targetType?: AuditLogDetailResponseTargetType;
  /** 대상 ID */
  targetId?: string;
  /** 설명 */
  description?: string;
  /** 요청 경로 */
  requestPath?: string;
  /** HTTP 메서드 */
  requestMethod?: string;
  /** 요청 본문 (민감정보 마스킹) */
  requestBody?: string;
  /** 응답 상태 코드 */
  responseStatus?: number;
  /** 응답 상태 설명 (관리자용) */
  responseStatusDescription?: string;
  /** IP 주소 */
  ipAddress?: string;
  /** User-Agent */
  userAgent?: string;
  /** 생성 일시 */
  createdAt: string;
}
