/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 감사 로그 대상 타입
 */
export enum AuditTargetType {
  USER= 'USER',
  BOOKING= 'BOOKING',
  PAYMENT= 'PAYMENT',
  PERFORMANCE= 'PERFORMANCE',
  SCHEDULE= 'SCHEDULE',
  VENUE= 'VENUE',
  SEAT= 'SEAT',
  NOTICE= 'NOTICE',

}