/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { AvailableCouponResponseDiscountMethod } from './availableCouponResponseDiscountMethod';

/**
 * 사용 가능한 쿠폰 응답
 */
export interface AvailableCouponResponse {
  /** 쿠폰 ID */
  id: number;
  /** 쿠폰명 */
  name: string;
  /** 쿠폰 설명 */
  description?: string;
  /** 할인 방식 */
  discountMethod: AvailableCouponResponseDiscountMethod;
  /** 할인값 */
  discountValue: number;
  /** 최대 할인금액 */
  maxDiscountAmount?: number;
  /** 최소 주문금액 */
  minOrderAmount?: number;
  /** 남은 사용 횟수 (null=무제한) */
  remainingUsage?: number;
  /** 유효 종료일 */
  validUntil: string;
}
