/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 사용 가능한 쿠폰 응답
 */
export interface AvailableCouponResponse {
  /** 쿠폰 ID */
  id: number;
  /** 쿠폰명 */
  name: string;
  /** 할인율 */
  discountRate: number;
  /** 유효 종료일 */
  validUntil: string;
  /** 정렬 순서 */
  sortOrder: number;
}
