/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 예매 좌석 응답
 */
export interface BookingSeatResponse {
  /** 예매 좌석 ID */
  id: number;
  /** 좌석 구역 */
  section: string;
  /** 행 번호 */
  row: number;
  /** 열 번호 */
  col: number;
}
