/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { BookingStatus } from './bookingStatus';
import type { BookingSeatResponse } from './bookingSeatResponse';
import type { PaymentDetailResponse } from './paymentDetailResponse';

/**
 * 예매 상세 내역 응답
 */
export interface BookingDetailResponse {
  /** 예매 ID */
  bookingId: string;
  /** 예매 번호 */
  bookingNumber: string;
  /** 공연 ID */
  performanceId: number;
  /** 공연 제목 */
  performanceTitle: string;
  /** 공연 메인 이미지 URL */
  mainImageUrl?: string;
  /** 공연 일시 */
  showDateTime: string;
  status: BookingStatus;
  /** 총 결제 금액 */
  totalPrice: number;
  /** 예매 일시 */
  createdAt: string;
  /** 좌석 목록 */
  seats: BookingSeatResponse[];
  /** 사용자 이메일 (관리자용) */
  userEmail?: string;
  /** 사용자 이름 (관리자용) */
  username?: string;
  paymentDetail?: PaymentDetailResponse;
}
