/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { BookingSeatResponseGrade } from './bookingSeatResponseGrade';

/**
 * 예매 좌석 응답
 */
export interface BookingSeatResponse {
  /** 예매 좌석 ID */
  id: number;
  /** 좌석 구역 */
  section: string;
  /** 좌석 열 */
  rowName: string;
  /** 좌석 번호 */
  seatNumber: number;
  /** 좌석 등급 */
  grade: BookingSeatResponseGrade;
  /** 좌석 가격 */
  price: number;
}
