/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { BookingSeatResponse } from './bookingSeatResponse';
import type { BookingResponseStatus } from './bookingResponseStatus';

/**
 * 예매 상세 응답
 */
export interface BookingResponse {
  /** 예매 ID */
  bookingId: string;
  /** 예매 번호 */
  bookingNumber: string;
  /** 만료 시각 (ISO 8601) */
  expiresAt: string;
  /** 남은 시간 (초) */
  remainingSeconds: number;
  /** 예매 좌석 목록 */
  seats: BookingSeatResponse[];
  /** 총 결제 금액 */
  totalPrice: number;
  /** 예매 상태 */
  status: BookingResponseStatus;
}
