/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSeatRequest } from './createSeatRequest';

/**
 * 좌석 일괄 생성 요청 DTO
 */
export interface BulkCreateSeatRequest {
  /** 생성할 좌석 목록 */
  seats: CreateSeatRequest[];
}
