/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { SeatResponse } from './seatResponse';

/**
 * 좌석 일괄 생성 결과 응답 DTO
 */
export interface BulkCreateSeatResponse {
  /** 생성된 좌석 수 */
  createdCount: number;
  /** 생성된 좌석 목록 */
  seats: SeatResponse[];
}
