/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 판매자 정보 응답 DTO
 */
export interface CompanyResponse {
  /** 회사 ID */
  id: number;
  /** 상호 */
  name: string;
  /** 대표자명 */
  ceoName?: string;
  /** 사업자등록번호 */
  businessNumber: string;
  /** 이메일 */
  email?: string;
  /** 연락처 */
  contact?: string;
  /** 주소 */
  address?: string;
  /** 공연 문의 연락처/이메일 */
  performanceInquiry?: string;
}
