/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 판매자 생성/수정 요청 DTO
 */
export interface CompanyRequest {
  /** 상호 */
  name: string;
  /** 대표자명 */
  ceoName?: string;
  /**
   * 사업자등록번호
   * @pattern ^(\d{3}-\d{2}-\d{5}|\d{10})$
   */
  businessNumber: string;
  /** 이메일 */
  email?: string;
  /** 연락처 */
  contact?: string;
  /** 주소 */
  address?: string;
  /** 공연 문의 연락처/이메일 */
  performanceInquiry?: string;
}
