/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 이전 기간 대비 비교 데이터
 */
export interface ComparisonData {
  /** 매출 변화율 (%) */
  revenueChangePercent: number;
  /** 예매 건수 변화율 (%) */
  bookingsChangePercent: number;
}
