/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 쿠폰 수정 요청 (관리자)
 */
export interface CouponUpdateRequest {
  /** 쿠폰명 */
  name: string;
  /**
   * 할인율 (%)
   * @minimum 1
   */
  discountRate: number;
  /** 유효 시작일 */
  validFrom: string;
  /** 유효 종료일 */
  validUntil: string;
  /** 정렬 순서 (낮을수록 먼저 표시) */
  sortOrder: number;
  /** 활성화 여부 */
  isActive: boolean;
}
