/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { SeatCouponRequest } from './seatCouponRequest';

/**
 * 쿠폰 검증 요청
 */
export interface CouponValidateRequest {
  /** 좌석별 쿠폰 적용 목록 */
  seatCoupons: SeatCouponRequest[];
}
