/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { CouponCreateRequestDiscountMethod } from './couponCreateRequestDiscountMethod';

/**
 * 쿠폰 생성 요청 (관리자)
 */
export interface CouponCreateRequest {
  /** 쿠폰명 */
  name: string;
  /** 쿠폰 설명 */
  description?: string;
  /** 할인 방식 */
  discountMethod: CouponCreateRequestDiscountMethod;
  /**
   * 할인값 (정액: 원, 정률: %)
   * @minimum 1
   */
  discountValue: number;
  /** 최대 할인금액 (정률 할인 시) */
  maxDiscountAmount?: number;
  /** 최소 주문금액 */
  minOrderAmount?: number;
  /** 1인당 최대 사용 횟수 (null=무제한) */
  maxUsagePerUser?: number;
  /** 유효 시작일 */
  validFrom: string;
  /** 유효 종료일 */
  validUntil: string;
}
