/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { SeatCouponResult } from './seatCouponResult';

/**
 * 쿠폰 검증 응답
 */
export interface CouponValidateResponse {
  /** 좌석별 적용 결과 */
  results: SeatCouponResult[];
  /** 총 원가 */
  totalOriginalPrice: number;
  /** 총 할인금액 */
  totalDiscountAmount: number;
  /** 총 최종가격 */
  totalFinalPrice: number;
  /** 전체 검증 성공 여부 */
  allValid: boolean;
}
