/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 예매 생성 요청 DTO
 */
export interface CreateReservationRequest {
  /** 회차별 좌석등급 재고 ID */
  scheduleTicketStockId: number;
  /**
   * 예매 수량 (최대 10매)
   * @minimum 1
   * @maximum 10
   */
  quantity: number;
  /**
   * 예매자 이름
   * @minLength 0
   * @maxLength 100
   */
  userName: string;
  /**
   * 예매자 연락처
   * @pattern ^01[0-9]-?\d{3,4}-?\d{4}$
   */
  userPhone: string;
  /** 예매자 이메일 */
  userEmail?: string;
}
