/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 회차별 좌석등급 재고 생성 요청 DTO
 */
export interface CreateScheduleTicketStockRequest {
  /** 공연 회차 ID */
  scheduleId: number;
  /** 좌석 등급 ID */
  ticketOptionId: number;
  /**
   * 총 좌석 수
   * @minimum 0
   */
  totalQuantity: number;
}
