/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 공연 생성 요청 DTO
 */
export interface CreatePerformanceRequest {
  /**
   * 공연명
   * @minLength 0
   * @maxLength 255
   */
  title: string;
  /** 공연 설명 */
  description?: string;
  /** 카테고리 */
  category: string;
  /** 공연 시간 (분) */
  runningTime?: number;
  /** 관람 연령 */
  ageRating?: string;
  /** 대표 이미지 URL */
  mainImageUrl?: string;
  /** 공연장 ID */
  venueId?: number;
  /** 공연 시작일 */
  startDate: string;
  /** 공연 종료일 */
  endDate: string;
}
