/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 카테고리
 */
export type CreateTicketingNoticeRequestCategory = typeof CreateTicketingNoticeRequestCategory[keyof typeof CreateTicketingNoticeRequestCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateTicketingNoticeRequestCategory = {
  BOOKING_NOTICE: 'BOOKING_NOTICE',
  BANK_TRANSFER: 'BANK_TRANSFER',
  TICKET_PICKUP: 'TICKET_PICKUP',
  MOBILE_TICKET: 'MOBILE_TICKET',
  REFUND: 'REFUND',
  CANCELLATION: 'CANCELLATION',
} as const;
