/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 좌석 선택 예매 요청 DTO
 */
export interface CreateSeatReservationRequest {
  /** 예매할 좌석 ID 목록 */
  scheduleSeatIds: number[];
  /**
   * 예매자 이름
   * @minLength 0
   * @maxLength 100
   */
  userName: string;
  /**
   * 예매자 연락처
   * @minLength 0
   * @maxLength 20
   */
  userPhone: string;
  /**
   * 예매자 이메일
   * @minLength 0
   * @maxLength 255
   */
  userEmail?: string;
  /** 세션 ID (비회원용) */
  sessionId?: string;
}
