/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 공지사항 카테고리 (SYSTEM: 시스템 점검, BOOKING_NOTICE: 예매 유의사항, EVENT: 이벤트)
 */
export type CreateNoticeRequestCategory = typeof CreateNoticeRequestCategory[keyof typeof CreateNoticeRequestCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateNoticeRequestCategory = {
  SYSTEM: 'SYSTEM',
  BOOKING_NOTICE: 'BOOKING_NOTICE',
  EVENT: 'EVENT',
} as const;
