/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 공연장 생성 요청 DTO
 */
export interface CreateVenueRequest {
  /**
   * 생성할 공연장 이름
   * @minLength 0
   * @maxLength 100
   */
  name: string;
  /**
   * 생성할 공연장 주소
   * @minLength 0
   * @maxLength 255
   */
  address?: string;
  /** 생성할 공연장 좌석 배치도 이미지 URL */
  seatingChartUrl?: string;
}
