/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 일별 매출 데이터
 */
export interface DailySalesData {
  /** 날짜 */
  date: string;
  /** 매출액 */
  revenue: number;
  /** 예매 건수 */
  bookings: number;
  /** 판매 티켓 수 */
  ticketsSold: number;
}
