/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { DatePeriod } from './datePeriod';
import type { DailySalesData } from './dailySalesData';

/**
 * 일별 매출 추이 응답
 */
export interface DailySalesResponse {
  period: DatePeriod;
  /** 총 매출액 */
  totalRevenue: number;
  /** 총 예매 건수 */
  totalBookings: number;
  /** 일별 데이터 */
  dailyData: DailySalesData[];
}
