/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { DatePeriod } from './datePeriod';
import type { ComparisonData } from './comparisonData';

/**
 * 대시보드 요약 응답
 */
export interface DashboardSummaryResponse {
  period: DatePeriod;
  /** 총 매출액 */
  totalRevenue: number;
  /** 총 예매 건수 */
  totalBookings: number;
  /** 확정 예매 건수 */
  confirmedBookings: number;
  /** 취소 예매 건수 */
  cancelledBookings: number;
  /** 만료 예매 건수 */
  expiredBookings: number;
  /** 평균 티켓 가격 */
  averageTicketPrice: number;
  /** 판매 티켓 수 */
  totalTicketsSold: number;
  comparisonWithPrevious?: ComparisonData;
}
