/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { DiscountStatsDiscountType } from './discountStatsDiscountType';

export interface DiscountStats {
  id: number;
  discountType: DiscountStatsDiscountType;
  date: string;
  usageCount: number;
  totalDiscountAmount: number;
  avgDiscountAmount: number;
  updatedAt: string;
}
