/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { DiscountStatsDiscountType } from './discountStatsDiscountType';

/**
 * 할인 수단별 통계 응답
 */
export interface DiscountStats {
  /** 통계 ID */
  id: number;
  /** 할인 유형 */
  discountType: DiscountStatsDiscountType;
  /** 날짜 */
  date: string;
  /** 사용 횟수 */
  usageCount: number;
  /** 총 할인 금액 */
  totalDiscountAmount: number;
  /** 평균 할인 금액 */
  avgDiscountAmount: number;
  /** 수정일시 */
  updatedAt: string;
}
