/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * API 에러 응답
 */
export interface ErrorResponse {
  /** 에러 코드 */
  errorCode: string;
  /** 에러 메시지 */
  message: string;
}
