/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

export type GetAuditLogsTargetType = typeof GetAuditLogsTargetType[keyof typeof GetAuditLogsTargetType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAuditLogsTargetType = {
  USER: 'USER',
  BOOKING: 'BOOKING',
  PAYMENT: 'PAYMENT',
  PERFORMANCE: 'PERFORMANCE',
  SCHEDULE: 'SCHEDULE',
  VENUE: 'VENUE',
  SEAT: 'SEAT',
  NOTICE: 'NOTICE',
} as const;
