/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuditLogsAction } from './getAuditLogsAction';
import type { GetAuditLogsCategory } from './getAuditLogsCategory';
import type { GetAuditLogsTargetType } from './getAuditLogsTargetType';
import type { Pageable } from './pageable';

export type GetAuditLogsParams = {
/**
 * 사용자 ID
 */
userId?: number;
/**
 * 액션 타입
 */
action?: GetAuditLogsAction;
/**
 * 카테고리
 */
category?: GetAuditLogsCategory;
/**
 * 대상 타입
 */
targetType?: GetAuditLogsTargetType;
/**
 * 대상 ID
 */
targetId?: string;
/**
 * 시작 일시 (ISO-8601)
 */
from?: string;
/**
 * 종료 일시 (ISO-8601)
 */
to?: string;
/**
 * 페이징 및 정렬 설정 (예: page=0&size=20&sort=createdAt,desc)
 */
pageable: Pageable;
};
