/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

export type GetDailySalesParams = {
/**
 * 조회 시작일
 */
startDate: string;
/**
 * 조회 종료일
 */
endDate: string;
/**
 * 공연 ID (선택)
 */
performanceId?: number;
};
