/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

export type GetMyHeldSeatsParams = {
/**
 * 세션 ID (비회원용)
 */
sessionId?: string;
};
