/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { SeatGrade } from './seatGrade';

/**
 * 등급별 판매 현황
 */
export interface GradeSalesDetail {
  grade: SeatGrade;
  /** 총 좌석 수 */
  totalSeats: number;
  /** 판매 좌석 수 */
  soldSeats: number;
  /** 대기중 좌석 수 */
  pendingSeats: number;
  /** 매출액 */
  revenue: number;
  /** 판매율 (%) */
  salesRate: number;
}
