/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { SeatGrade } from './seatGrade';

/**
 * 등급별 매출
 */
export interface GradeSalesResponse {
  grade: SeatGrade;
  /** 매출액 */
  revenue: number;
  /** 판매 티켓 수 */
  ticketsSold: number;
  /** 평균 가격 */
  averagePrice: number;
}
