/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 점유된 좌석 정보
 */
export interface HeldSeatInfo {
  /** 회차별 좌석 ID */
  scheduleSeatId: number;
  /** 표시 이름 */
  displayName: string;
  /** 좌석등급명 */
  ticketOptionName: string;
  /** 가격 */
  price: number;
  /** 점유 만료 시간 */
  heldUntil: string;
}
