/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { HeldSeatInfo } from './heldSeatInfo';

/**
 * 좌석 점유 응답 DTO
 */
export interface HoldSeatsResponse {
  /** 성공 여부 */
  success: boolean;
  /** 점유된 좌석 목록 */
  heldSeats: HeldSeatInfo[];
  /** 총 가격 */
  totalPrice: number;
  /** 점유 만료 시간 */
  expiresAt: string;
}
