/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { HomeSectionResponse } from './homeSectionResponse';

/**
 * 홈 화면 전체 섹션 응답 DTO
 */
export interface HomeSectionsResponse {
  /** 홈 화면을 구성하는 대분류 섹션 목록 (순서대로 노출) */
  sections: HomeSectionResponse[];
}
