/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 홈 화면용 공연 간략 정보 DTO
 */
export interface HomePerformanceResponse {
  /** 공연 ID (상세 페이지 이동 시 사용) */
  id: number;
  /** 공연 제목 */
  title: string;
  /** 메인 포스터 이미지 URL */
  mainImageUrl?: string;
  /** 공연 시작일 */
  startDate: string;
  /** 공연 종료일 */
  endDate: string;
  /** 공연장 이름 */
  venueName?: string;
}
