/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 섹션 코드 (예: POPULAR_TICKET, DATE_COURSE)
 */
export type HomeSectionResponseSection = typeof HomeSectionResponseSection[keyof typeof HomeSectionResponseSection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HomeSectionResponseSection = {
  POPULAR_TICKET: 'POPULAR_TICKET',
  DATE_COURSE: 'DATE_COURSE',
  RECOMMENDED: 'RECOMMENDED',
  REGION: 'REGION',
} as const;
