/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { HomeTagWithPerformancesResponseTag } from './homeTagWithPerformancesResponseTag';
import type { HomePerformanceResponse } from './homePerformanceResponse';

/**
 * 태그별 공연 목록 응답
 */
export interface HomeTagWithPerformancesResponse {
  /** 태그 코드 (예: MUSICAL, WEEKLY_OPEN) */
  tag: HomeTagWithPerformancesResponseTag;
  /** 태그 화면 표시명 (한글) */
  displayName: string;
  /** 태그 노출 순서 (탭 순서 등으로 활용) */
  displayOrder: number;
  /** 해당 태그에 속한 공연 목록 (관리자가 지정한 순서대로 정렬됨) */
  performances: HomePerformanceResponse[];
}
