/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { HomeSectionResponseSection } from './homeSectionResponseSection';
import type { HomeTagWithPerformancesResponse } from './homeTagWithPerformancesResponse';

/**
 * 홈 섹션 정보 응답
 */
export interface HomeSectionResponse {
  /** 섹션 코드 (예: POPULAR_TICKET, DATE_COURSE) */
  section: HomeSectionResponseSection;
  /** 섹션 화면 표시명 (한글) */
  displayName: string;
  /** 섹션 노출 순서 */
  displayOrder: number;
  /** 섹션에 포함된 하위 태그 및 공연 목록 */
  tags: HomeTagWithPerformancesResponse[];
}
