/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { InitializeScheduleSeatsRequestSeatGradeMapping } from './initializeScheduleSeatsRequestSeatGradeMapping';

/**
 * 회차별 좌석 초기화 요청 DTO
 */
export interface InitializeScheduleSeatsRequest {
  /** 좌석등급별 티켓옵션 ID 매핑 (SeatGrade -> TicketOption ID) */
  seatGradeMapping: InitializeScheduleSeatsRequestSeatGradeMapping;
}
