/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { NoticeCategory } from './noticeCategory';

/**
 * 공지사항 응답
 */
export interface NoticeResponse {
  /** 공지사항 ID */
  id: number;
  category: NoticeCategory;
  /** 카테고리 설명 */
  categoryDescription: string;
  /** 내용 */
  content: string;
  /** 활성화 여부 */
  isActive: boolean;
  /** 생성일시 */
  createdAt?: string;
  /** 수정일시 */
  updatedAt?: string;
}
