/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { NoticeCategory } from './noticeCategory';
import type { NoticeResponse } from './noticeResponse';

/**
 * 카테고리별 공지사항 그룹 응답
 */
export interface NoticeGroupResponse {
  category: NoticeCategory;
  /** 카테고리 설명 */
  categoryDescription: string;
  /** 공지사항 목록 */
  notices: NoticeResponse[];
}
