/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { WishlistResponse } from './wishlistResponse';
import type { WishlistMetaResponse } from './wishlistMetaResponse';

/**
 * 페이징 처리된 찜 목록 응답
 */
export interface PagedWishlistResponse {
  /** 찜 데이터 리스트 */
  data: WishlistResponse[];
  meta: WishlistMetaResponse;
}
