/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

export type PaymentMethodStatsPaymentMethod = typeof PaymentMethodStatsPaymentMethod[keyof typeof PaymentMethodStatsPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethodStatsPaymentMethod = {
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  VIRTUAL_ACCOUNT: 'VIRTUAL_ACCOUNT',
  KAKAO_PAY: 'KAKAO_PAY',
  NAVER_PAY: 'NAVER_PAY',
  TOSS_PAY: 'TOSS_PAY',
  PAYCO: 'PAYCO',
  POINT: 'POINT',
} as const;
