/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentCreateRequestPaymentMethod } from './paymentCreateRequestPaymentMethod';
import type { AppliedDiscountDto } from './appliedDiscountDto';

export interface PaymentCreateRequest {
  bookingId: string;
  paymentMethod: PaymentCreateRequestPaymentMethod;
  totalAmount: number;
  ticketAmount: number;
  bookingFee: number;
  originalPrice: number;
  isAgreed: boolean;
  discounts: AppliedDiscountDto[];
}
