/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentDiscountResponseType } from './paymentDiscountResponseType';

/**
 * 할인 정보 응답
 */
export interface PaymentDiscountResponse {
  /** 할인 유형 */
  type: PaymentDiscountResponseType;
  /** 할인 명칭 */
  name: string;
  /** 할인 금액 */
  amount: number;
  /** 쿠폰 ID */
  couponId?: number;
  /** 적용된 좌석 ID */
  bookingSeatId?: number;
}
