/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { SeatGrade } from './seatGrade';

/**
 * 결제 항목 정보
 */
export interface PaymentItemResponse {
  /** 공연 ID */
  performanceId: number;
  /** 공연명 */
  performanceTitle: string;
  seatGrade: SeatGrade;
  /** 구역 */
  section: string;
  /** 행 번호 */
  row: number;
  /** 열 번호 */
  col: number;
  /** 좌석 원가 */
  unitPrice: number;
  /** 항목 할인 금액 */
  discountAmount: number;
  /** 항목 최종 금액 (할인 적용 후) */
  finalPrice: number;
}
