/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentResponsePaymentMethod } from './paymentResponsePaymentMethod';
import type { PaymentResponsePaymentStatus } from './paymentResponsePaymentStatus';

/**
 * 결제 정보 응답
 */
export interface PaymentResponse {
  /** 결제 ID */
  id: string;
  /** 예매 ID */
  bookingId: string;
  /** 결제 번호 (주문 번호) */
  paymentNumber: string;
  /** 결제 수단 */
  paymentMethod: PaymentResponsePaymentMethod;
  /** 결제 상태 */
  paymentStatus: PaymentResponsePaymentStatus;
  /** 할인 전 금액 (원가) */
  originalPrice: number;
  /** 총 할인 금액 */
  discountAmount: number;
  /** 예매 수수료 */
  bookingFee: number;
  /** 최종 결제 금액 */
  finalPrice: number;
  /** 결제 요청 일시 */
  requestedAt: string;
  /** 결제 완료 일시 */
  completedAt?: string;
}
