/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentResponse } from './paymentResponse';
import type { PaymentItemResponse } from './paymentItemResponse';
import type { PaymentDiscountResponse } from './paymentDiscountResponse';
import type { PgInfoResponse } from './pgInfoResponse';

/**
 * 결제 상세 정보 응답
 */
export interface PaymentDetailResponse {
  payment: PaymentResponse;
  /** 결제 항목 목록 (티켓 등) */
  items: PaymentItemResponse[];
  /** 할인 적용 상세 내역 */
  discounts: PaymentDiscountResponse[];
  pgInfo?: PgInfoResponse;
}
