/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 결제 상태
 */
export type PaymentResponsePaymentStatus = typeof PaymentResponsePaymentStatus[keyof typeof PaymentResponsePaymentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentResponsePaymentStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  PARTIAL_REFUNDED: 'PARTIAL_REFUNDED',
} as const;
