/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { PerformanceSearchResponse } from './performanceSearchResponse';

export interface PerformanceSearchListResponse {
  /** 검색 결과 목록 */
  content: PerformanceSearchResponse[];
  /** 전체 데이터 개수 */
  totalElements: number;
  /** 다음 페이지 존재 여부 */
  hasNextPage: boolean;
}
