/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { PerformanceInfo } from './performanceInfo';
import type { SalesSummary } from './salesSummary';
import type { GradeSalesResponse } from './gradeSalesResponse';
import type { ScheduleSalesSummary } from './scheduleSalesSummary';
import type { DailySalesData } from './dailySalesData';

/**
 * 공연 상세 매출 응답
 */
export interface PerformanceDetailSalesResponse {
  performance: PerformanceInfo;
  summary: SalesSummary;
  /** 등급별 매출 */
  revenueByGrade: GradeSalesResponse[];
  /** 회차별 매출 */
  schedules: ScheduleSalesSummary[];
  /** 일별 매출 */
  dailySales: DailySalesData[];
}
