/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { PerformanceHomeTagResponseTag } from './performanceHomeTagResponseTag';
import type { PerformanceHomeTagResponseSection } from './performanceHomeTagResponseSection';

/**
 * 홈 태그 매핑 응답 (관리자용)
 */
export interface PerformanceHomeTagResponse {
  /** 태그 매핑 고유 ID */
  id: number;
  /** 홈 섹션 태그 코드 */
  tag: PerformanceHomeTagResponseTag;
  /** 태그 화면 표시명 (한글) */
  tagDisplayName: string;
  /** 상위 섹션 코드 */
  section: PerformanceHomeTagResponseSection;
  /** 섹션 화면 표시명 (한글) */
  sectionDisplayName: string;
  /** 태그 내 노출 순서 */
  displayOrder: number;
  /** 자동 태깅 여부 (지역 태그 등 시스템에 의해 자동 생성된 경우 true) */
  isAutoTagged: boolean;
  /** 생성일시 */
  createdAt?: string;
}
