/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { VenueResponse } from './venueResponse';
import type { CompanyResponse } from './companyResponse';

/**
 * 공연 정보 응답 DTO
 */
export interface PerformanceResponse {
  /** 공연 ID */
  id: number;
  /** 공연명 */
  title: string;
  /** 공연 상세 설명 */
  description?: string;
  /** 공연 카테고리 */
  category: string;
  /** 공연 시간 (분) */
  runningTime?: number;
  /** 공연 관람 연령 */
  ageRating?: string;
  /** 공연 대표 이미지 URL */
  mainImageUrl?: string;
  /** 공연 노출 여부 */
  visible: boolean;
  venue?: VenueResponse;
  /** 공연 시작일 */
  startDate: string;
  /** 공연 종료일 */
  endDate: string;
  /** 출연진 */
  actors?: string;
  /** 기획사 */
  agency?: string;
  /** 제작사 */
  producer?: string;
  /** 주최 */
  host?: string;
  /** 할인정보 */
  discountInfo?: string;
  /** 이용안내 */
  usageGuide?: string;
  /** 취소/환불규정 */
  refundPolicy?: string;
  /** 상품상세 이미지 URL */
  detailImageUrl?: string;
  company?: CompanyResponse;
  /** 예매 수수료 */
  bookingFee?: number;
  /** 배송 안내 */
  shippingGuide?: string;
  /** 공연 정보 생성일시 */
  createdAt?: string;
  /** 공연 정보 수정일시 */
  updatedAt?: string;
}
