/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { DatePeriod } from './datePeriod';

/**
 * 공연별 매출 응답
 */
export interface PerformanceSalesResponse {
  /** 공연 ID */
  performanceId: number;
  /** 공연 제목 */
  title: string;
  /** 카테고리 */
  category: string;
  /** 공연장명 */
  venue?: string;
  period: DatePeriod;
  /** 총 매출액 */
  totalRevenue: number;
  /** 총 예매 건수 */
  totalBookings: number;
  /** 확정 예매 건수 */
  confirmedBookings: number;
  /** 취소 예매 건수 */
  cancelledBookings: number;
  /** 판매 티켓 수 */
  totalTicketsSold: number;
  /** 평균 티켓 가격 */
  averageTicketPrice: number;
  /** 판매율 (%) */
  salesRate: number;
}
