/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 공연 순서 항목
 */
export interface PerformanceOrderItem {
  /** 순서를 변경할 공연의 ID */
  performanceId: number;
  /**
   * 변경할 노출 순서 (낮을수록 먼저 표시)
   * @minimum 0
   */
  displayOrder: number;
}
