/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 공연 검색 정렬 방식
 */
export enum PerformanceSearchSort {
  BOOKING_COUNT= 'BOOKING_COUNT',
  END_DATE_ASC= 'END_DATE_ASC',
  CREATED_AT_DESC= 'CREATED_AT_DESC',

}