/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 검색 결과 목록
 */
export interface PerformanceSearchResponse {
  /** 공연 ID */
  id: number;
  /** 공연 제목 */
  title: string;
  /** 공연 대표 이미지 URL */
  mainImageUrl?: string;
  /** 카테고리 */
  category: string;
  /** 지역명 */
  regionName?: string;
  /** 공연장 주소 */
  venueAddress?: string;
  /** 공연 시작일 */
  startDate: string;
  /** 공연 종료일 */
  endDate: string;
}
