/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { PerformanceSearchStatus } from './performanceSearchStatus';
import type { Region } from './region';
import type { PerformanceSearchSort } from './performanceSearchSort';

export interface PerformanceSearchRequest {
  /** 검색어 (제목, 카테고리, 공연장 주소 통합 검색) */
  keyword?: string;
  /** 판매 상태 필터 (다중 선택 가능) */
  status?: PerformanceSearchStatus[];
  /** 장르(카테고리) 필터 (다중 선택 가능) */
  category?: string[];
  /** 지역 필터 (다중 선택 가능) */
  region?: Region[];
  sort?: PerformanceSearchSort;
  /** 페이지 번호 (0-based) */
  page: number;
  /** 페이지 크기 */
  size: number;
}
