/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { DatePeriod } from './datePeriod';

/**
 * 공연 기본 정보
 */
export interface PerformanceInfo {
  /** 공연 ID */
  id: number;
  /** 공연 제목 */
  title: string;
  /** 카테고리 */
  category: string;
  /** 공연장명 */
  venue?: string;
  period: DatePeriod;
}
