/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 홈 섹션 태그 코드
 */
export type PerformanceHomeTagResponseTag = typeof PerformanceHomeTagResponseTag[keyof typeof PerformanceHomeTagResponseTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PerformanceHomeTagResponseTag = {
  WEEKLY_OPEN: 'WEEKLY_OPEN',
  MUSICAL: 'MUSICAL',
  CONCERT: 'CONCERT',
  THEATER: 'THEATER',
  EXHIBITION: 'EXHIBITION',
  DATE_MUSICAL: 'DATE_MUSICAL',
  DATE_THEATER: 'DATE_THEATER',
  DATE_CLASSIC: 'DATE_CLASSIC',
  DATE_EXHIBITION: 'DATE_EXHIBITION',
  LIMITED_SALE: 'LIMITED_SALE',
  WITH_KIDS: 'WITH_KIDS',
  DAEHAKRO: 'DAEHAKRO',
  REGION_SEOUL: 'REGION_SEOUL',
  REGION_GYEONGGI: 'REGION_GYEONGGI',
  REGION_BUSAN: 'REGION_BUSAN',
  REGION_DAEGU: 'REGION_DAEGU',
  REGION_DAEJEON: 'REGION_DAEJEON',
  REGION_NATIONWIDE: 'REGION_NATIONWIDE',
} as const;
