/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * PG 결제 정보
 */
export interface PgInfoResponse {
  /** PG사 */
  provider: string;
  /** PG사 거래 ID */
  transactionId: string;
  /** 카드사 명 */
  cardCompany?: string;
  /** 카드 번호 (마스킹됨) */
  cardNumber?: string;
}
