/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { RecentBookingResponse } from './recentBookingResponse';

/**
 * 최근 예매 목록 응답
 */
export interface RecentBookingsResponse {
  /** 예매 목록 */
  bookings: RecentBookingResponse[];
}
