/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 최근 예매 응답
 */
export interface RecentBookingResponse {
  /** 예매 ID */
  bookingId: string;
  /** 예매 번호 */
  bookingNumber: string;
  /** 예매 상태 */
  status: string;
  /** 공연 제목 */
  performanceTitle: string;
  /** 공연 일시 */
  scheduleDate: string;
  /** 예매자명 (마스킹) */
  userName: string;
  /** 예매자 이메일 (마스킹) */
  userEmail: string;
  /** 티켓 수 */
  ticketCount: number;
  /** 총 금액 */
  totalPrice: number;
  /** 예매 일시 */
  createdAt: string;
}
