/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 토큰 갱신 요청 DTO
 */
export interface RefreshTokenRequest {
  /** Refresh Token */
  refreshToken: string;
}
