/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 좌석 해제 요청 DTO
 */
export interface ReleaseSeatsRequest {
  /** 해제할 좌석 ID 목록 */
  scheduleSeatIds: number[];
  /** 세션 ID (비회원용) */
  sessionId?: string;
}
