/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 좌석 해제 응답 DTO
 */
export interface ReleaseSeatsResponse {
  /** 성공 여부 */
  success: boolean;
  /** 해제된 좌석 수 */
  releasedCount: number;
}
