/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 예매 조회 요청 DTO (비회원)
 */
export interface ReservationLookupRequest {
  /** 예매 번호 */
  reservationNumber: string;
  /** 예매자 연락처 */
  userPhone: string;
}
