/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { ReservationResponseStatus } from './reservationResponseStatus';

/**
 * 예매 응답 DTO
 */
export interface ReservationResponse {
  /** 예매 ID */
  id: number;
  /** 예매 번호 */
  reservationNumber: string;
  /** 공연명 */
  performanceTitle: string;
  /** 공연 일시 */
  showDatetime: string;
  /** 좌석 등급 */
  ticketOptionName: string;
  /** 예매 수량 */
  quantity: number;
  /** 총 결제 금액 */
  totalPrice: number;
  /** 예매자 이름 */
  userName: string;
  /** 예매자 연락처 */
  userPhone: string;
  /** 예매자 이메일 */
  userEmail?: string;
  /** 예매 상태 */
  status: ReservationResponseStatus;
  /** 예매 일시 */
  reservedAt: string;
  /** 확정 일시 */
  confirmedAt?: string;
  /** 취소 일시 */
  cancelledAt?: string;
}
