/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 매출 요약
 */
export interface SalesSummary {
  /** 총 매출액 */
  totalRevenue: number;
  /** 총 예매 건수 */
  totalBookings: number;
  /** 확정 예매 건수 */
  confirmedBookings: number;
  /** 취소 예매 건수 */
  cancelledBookings: number;
  /** 만료 예매 건수 */
  expiredBookings: number;
  /** 판매 티켓 수 */
  totalTicketsSold: number;
  /** 총 좌석 수 */
  totalSeats: number;
  /** 판매율 (%) */
  salesRate: number;
}
