/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { SeatPositionResponse } from './seatPositionResponse';

/**
 * 회차별 좌석 상태 목록 응답 DTO
 */
export interface ScheduleSeatStatusResponse {
  /** 회차 ID */
  scheduleId: number;
  /** 점유 중인 좌석 목록 */
  pending: SeatPositionResponse[];
  /** 예약 완료된 좌석 목록 */
  reserved: SeatPositionResponse[];
}
