/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { SeatStatusResponse } from './seatStatusResponse';

/**
 * 회차별 좌석 상태 목록 응답 DTO
 */
export interface ScheduleSeatStatusResponse {
  /** 회차 ID */
  scheduleId: number;
  /** 좌석 상태 목록 (PENDING, RESERVED만 포함) */
  seats: SeatStatusResponse[];
}
