/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduleSectionSeatsResponse } from './scheduleSectionSeatsResponse';
import type { SeatStatusSummary } from './seatStatusSummary';

/**
 * 회차별 좌석 목록 응답 DTO (좌석배치도용)
 */
export interface ScheduleSeatMapResponse {
  /** 회차 ID */
  scheduleId: number;
  /** 공연 제목 */
  performanceTitle: string;
  /** 공연 일시 */
  showDatetime: string;
  /** 공연장 이름 */
  venueName: string;
  /** 구역별 좌석 목록 */
  sections: ScheduleSectionSeatsResponse[];
  summary: SeatStatusSummary;
}
