/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduleInfo } from './scheduleInfo';
import type { ScheduleSalesDetail } from './scheduleSalesDetail';
import type { GradeSalesDetail } from './gradeSalesDetail';
import type { RecentBookingResponse } from './recentBookingResponse';

/**
 * 회차 판매 현황 응답
 */
export interface ScheduleSalesResponse {
  schedule: ScheduleInfo;
  sales: ScheduleSalesDetail;
  /** 등급별 판매 현황 */
  salesByGrade: GradeSalesDetail[];
  /** 최근 예매 내역 */
  recentBookings: RecentBookingResponse[];
}
