/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 회차별 좌석등급 재고 응답 DTO
 */
export interface ScheduleTicketStockResponse {
  /** 재고 ID */
  id: number;
  /** 공연 회차 ID */
  scheduleId: number;
  /** 공연 일시 */
  showDatetime: string;
  /** 좌석 등급 ID */
  ticketOptionId: number;
  /** 좌석 등급명 */
  ticketOptionName: string;
  /** 좌석 가격 */
  price: number;
  /** 총 좌석 수 */
  totalQuantity: number;
  /** 잔여 좌석 수 */
  remainingQuantity: number;
  /** 매진 여부 */
  soldOut: boolean;
}
