/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 회차 정보
 */
export interface ScheduleInfo {
  /** 회차 ID */
  id: number;
  /** 공연 ID */
  performanceId: number;
  /** 공연 제목 */
  performanceTitle: string;
  /** 공연 일시 */
  performanceDate: string;
  /** 공연장명 */
  venue?: string;
}
