/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduleSeatResponseSeatGrade } from './scheduleSeatResponseSeatGrade';
import type { ScheduleSeatResponseStatus } from './scheduleSeatResponseStatus';

/**
 * 회차별 좌석 상태 응답 DTO
 */
export interface ScheduleSeatResponse {
  /** 회차별 좌석 ID */
  scheduleSeatId: number;
  /** 좌석 ID */
  seatId: number;
  /** 좌석 열 */
  row: string;
  /** 좌석 번호 */
  number: number;
  /** 구역 */
  section: string;
  /** 표시 이름 */
  displayName: string;
  /** 좌석배치도 X좌표 */
  positionX: number;
  /** 좌석배치도 Y좌표 */
  positionY: number;
  /** 좌석 등급 */
  seatGrade: ScheduleSeatResponseSeatGrade;
  /** 좌석 상태 */
  status: ScheduleSeatResponseStatus;
  /** 좌석등급 ID */
  ticketOptionId: number;
  /** 좌석등급명 */
  ticketOptionName: string;
  /** 가격 */
  price: number;
  /** 내가 점유한 좌석인지 여부 */
  isMyHold: boolean;
}
