/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { PerformanceSearchStatus } from './performanceSearchStatus';
import type { Region } from './region';
import type { PerformanceSearchSort } from './performanceSearchSort';

export type SearchParams = {
keyword?: string;
status?: PerformanceSearchStatus[];
category?: string[];
region?: Region[];
sort?: PerformanceSearchSort;
page?: number;
size?: number;
};
