/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

export type SeatStatusEventStatus = typeof SeatStatusEventStatus[keyof typeof SeatStatusEventStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SeatStatusEventStatus = {
  AVAILABLE: 'AVAILABLE',
  HELD: 'HELD',
  RESERVED: 'RESERVED',
  UNAVAILABLE: 'UNAVAILABLE',
} as const;
