/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { SeatingChartResponseSeatingChart } from './seatingChartResponseSeatingChart';
import type { VenueSeatCapacityResponse } from './venueSeatCapacityResponse';

/**
 * 좌석 배치도 응답 DTO
 */
export interface SeatingChartResponse {
  /** 공연장 ID */
  venueId: number;
  /** 좌석 배치도 JSON 객체 */
  seatingChart?: SeatingChartResponseSeatingChart;
  /** 등급별 좌석 수 목록 */
  seatCapacities?: VenueSeatCapacityResponse[];
}
