/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 예매 상태
 */
export type SeatReservationResponseStatus = typeof SeatReservationResponseStatus[keyof typeof SeatReservationResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SeatReservationResponseStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
} as const;
