/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { SeatPositionRequest } from './seatPositionRequest';

/**
 * 좌석 점유 요청 DTO
 */
export interface SeatHoldRequest {
  /** 점유할 좌석 목록 (최대 4석) */
  seats: SeatPositionRequest[];
}
