/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { SeatingChartRequestSeatingChart } from './seatingChartRequestSeatingChart';
import type { VenueSeatCapacityRequest } from './venueSeatCapacityRequest';

/**
 * 좌석 배치도 저장 요청 DTO
 */
export interface SeatingChartRequest {
  /** 좌석 배치도 JSON 객체 */
  seatingChart: SeatingChartRequestSeatingChart;
  /** 등급별 좌석 수 목록 (배치도와 함께 저장) */
  seatCapacities?: VenueSeatCapacityRequest[];
}
