/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { SeatStatusResponse } from './seatStatusResponse';

/**
 * 좌석 점유 응답 DTO
 */
export interface SeatHoldResponse {
  /** 회차 ID */
  scheduleId: number;
  /** 점유된 좌석 목록 */
  heldSeats: SeatStatusResponse[];
  /** 점유 만료 시간 */
  expiresAt: string;
}
