/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { SeatResponseSeatGrade } from './seatResponseSeatGrade';

/**
 * 좌석 정보 응답 DTO
 */
export interface SeatResponse {
  /** 좌석 ID */
  id: number;
  /** 공연장 ID */
  venueId: number;
  /** 구역 */
  section: string;
  /** 좌석 열 */
  row: string;
  /** 좌석 번호 */
  number: number;
  /** 좌석 등급 */
  seatGrade: SeatResponseSeatGrade;
  /** 표시 이름 */
  displayName: string;
  /** 좌석배치도 X좌표 */
  positionX: number;
  /** 좌석배치도 Y좌표 */
  positionY: number;
  /** 생성일시 */
  createdAt?: string;
  /** 수정일시 */
  updatedAt?: string;
}
