/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 좌석별 쿠폰 적용 요청
 */
export interface SeatCouponRequest {
  /** 좌석 ID (BookingItem ID) */
  seatId: number;
  /** 적용할 쿠폰 ID */
  couponId: number;
  /**
   * 좌석 원가
   * @minimum 1
   */
  originalPrice: number;
}
