/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 좌석 등급
 */
export type SeatResponseSeatGrade = typeof SeatResponseSeatGrade[keyof typeof SeatResponseSeatGrade];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SeatResponseSeatGrade = {
  STANDARD: 'STANDARD',
  PREMIUM: 'PREMIUM',
  VIP: 'VIP',
  ACCESSIBLE: 'ACCESSIBLE',
} as const;
