/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { SeatStatusEventStatus } from './seatStatusEventStatus';

export interface SeatStatusEvent {
  scheduleSeatId: number;
  status?: SeatStatusEventStatus;
  timestamp: string;
  isHeartbeat: boolean;
}
