/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 좌석 상태
 */
export type SeatStatusResponseStatus = typeof SeatStatusResponseStatus[keyof typeof SeatStatusResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SeatStatusResponseStatus = {
  PENDING: 'PENDING',
  RESERVED: 'RESERVED',
} as const;
