/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 좌석 배치도 JSON 객체
 */
export type SeatingChartResponseSeatingChart = { [key: string]: unknown };
