/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 좌석 상태 요약
 */
export interface SeatStatusSummary {
  /** 총 좌석 수 */
  total: number;
  /** 예매 가능 좌석 수 */
  available: number;
  /** 점유 중인 좌석 수 */
  held: number;
  /** 예매 완료 좌석 수 */
  reserved: number;
}
