/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { SeatStatusResponseStatus } from './seatStatusResponseStatus';

/**
 * 좌석 상태 응답 DTO
 */
export interface SeatStatusResponse {
  /** 행 번호 */
  row: number;
  /** 열 번호 */
  col: number;
  /** 좌석 상태 */
  status: SeatStatusResponseStatus;
}
