/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 좌석별 쿠폰 적용 결과
 */
export interface SeatCouponResult {
  /** 좌석 ID */
  seatId: number;
  /** 쿠폰 ID */
  couponId: number;
  /** 원가 */
  originalPrice: number;
  /** 할인금액 */
  discountAmount: number;
  /** 최종가격 */
  finalPrice: number;
  /** 적용 가능 여부 */
  isValid: boolean;
  /** 메시지 (오류 시) */
  message?: string;
}
