/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { SeatResponse } from './seatResponse';

/**
 * 구역별 좌석 목록
 */
export interface SectionSeatsResponse {
  /** 구역명 */
  name: string;
  /** 좌석 목록 */
  seats: SeatResponse[];
}
