/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { SeatPositionRequest } from './seatPositionRequest';

/**
 * 예매 시작 요청 - 좌석 일괄 점유
 */
export interface StartBookingRequest {
  /** 공연 회차 ID */
  scheduleId: number;
  /**
   * 선택한 좌석 목록 (최대 4석)
   * @minItems 0
   * @maxItems 4
   */
  seats: SeatPositionRequest[];
}
