/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 태그 내 공연 목록 응답 (관리자용)
 */
export interface TagPerformanceResponse {
  /** 태그 매핑 고유 ID (삭제 시 사용) */
  tagId: number;
  /** 공연 ID */
  performanceId: number;
  /** 공연 제목 */
  title: string;
  /** 공연 메인 이미지 URL */
  mainImageUrl?: string;
  /** 태그 내 노출 순서 */
  displayOrder: number;
  /** 자동 태깅 여부 */
  isAutoTagged: boolean;
  /** 공연 노출 여부 (false인 경우 사용자 홈 화면에는 노출되지 않음) */
  visible: boolean;
}
