/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { TicketOptionResponseSeatGrade } from './ticketOptionResponseSeatGrade';

/**
 * 티켓 옵션 응답 DTO
 */
export interface TicketOptionResponse {
  /** 티켓 옵션 ID */
  id: number;
  /** 좌석 등급 */
  seatGrade: TicketOptionResponseSeatGrade;
  /** 가격 */
  price: number;
}
