/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { TicketOptionRequestSeatGrade } from './ticketOptionRequestSeatGrade';

/**
 * 티켓 옵션 생성/수정 요청 DTO
 */
export interface TicketOptionRequest {
  /** 좌석 등급 */
  seatGrade: TicketOptionRequestSeatGrade;
  /** 가격 */
  price: number;
}
