/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 등급별 잔여석 정보 DTO
 */
export interface TicketOptionWithRemainingSeatsResponse {
  /** 좌석 등급 */
  seatGrade: string;
  /** 잔여석 수 */
  remainingSeats: number;
}
