/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { TicketingNoticeResponseCategory } from './ticketingNoticeResponseCategory';

/**
 * 예매 안내사항 응답
 */
export interface TicketingNoticeResponse {
  /** 안내사항 ID */
  id: number;
  /** 카테고리 */
  category: TicketingNoticeResponseCategory;
  /** 카테고리 설명 */
  categoryDescription: string;
  /** 제목 */
  title: string;
  /** 내용 */
  content: string;
  /** 정렬 순서 */
  displayOrder: number;
  /** 활성화 여부 */
  isActive: boolean;
  /** 생성일시 */
  createdAt?: string;
  /** 수정일시 */
  updatedAt?: string;
}
