/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { TicketingNoticeGroupResponseCategory } from './ticketingNoticeGroupResponseCategory';
import type { TicketingNoticeResponse } from './ticketingNoticeResponse';

/**
 * 카테고리별 안내사항 그룹 응답
 */
export interface TicketingNoticeGroupResponse {
  /** 카테고리 */
  category: TicketingNoticeGroupResponseCategory;
  /** 카테고리 설명 */
  categoryDescription: string;
  /** 안내사항 목록 */
  notices: TicketingNoticeResponse[];
}
