/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 공연장 수정 요청 DTO
 */
export interface UpdateVenueRequest {
  /**
   * 수정할 공연장 이름
   * @minLength 0
   * @maxLength 100
   */
  name: string;
  /**
   * 수정할 공연장 주소
   * @minLength 0
   * @maxLength 255
   */
  address?: string;
  /**
   * 공연장 대표번호
   * @minLength 0
   * @maxLength 50
   */
  phoneNumber?: string;
}
