/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 공연 수정 요청 DTO
 */
export interface UpdatePerformanceRequest {
  /**
   * 수정할 공연명
   * @minLength 0
   * @maxLength 255
   */
  title: string;
  /** 수정할 공연 상세 설명 */
  description?: string;
  /** 수정할 공연 카테고리 */
  category: string;
  /** 수정할 공연 시간 (분) */
  runningTime?: number;
  /** 수정할 공연 관람 연령 */
  ageRating?: string;
  /** 수정할 공연 대표 이미지 URL */
  mainImageUrl?: string;
  /** 공연 노출 여부 */
  visible: boolean;
  /** 공연이 열릴 공연장 ID */
  venueId?: number;
  /** 수정할 공연 시작일 */
  startDate: string;
  /** 수정할 공연 종료일 */
  endDate: string;
}
