/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateTicketingNoticeRequestCategory } from './updateTicketingNoticeRequestCategory';

/**
 * 예매 안내사항 수정 요청
 */
export interface UpdateTicketingNoticeRequest {
  /** 카테고리 */
  category: UpdateTicketingNoticeRequestCategory;
  /**
   * 제목
   * @minLength 0
   * @maxLength 255
   */
  title: string;
  /** 내용 */
  content: string;
  /** 정렬 순서 */
  displayOrder: number;
  /** 활성화 여부 */
  isActive: boolean;
}
