/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { PerformanceOrderItem } from './performanceOrderItem';

/**
 * 태그 내 공연 순서 변경 요청 DTO
 */
export interface UpdateDisplayOrderRequest {
  /** 순서를 변경할 공연 목록 */
  performanceOrders: PerformanceOrderItem[];
}
