/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 회차별 좌석등급 재고 수정 요청 DTO
 */
export interface UpdateScheduleTicketStockRequest {
  /**
   * 총 좌석 수
   * @minimum 0
   */
  totalQuantity: number;
  /**
   * 잔여 좌석 수
   * @minimum 0
   */
  remainingQuantity: number;
}
