/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateSeatRequestSeatGrade } from './updateSeatRequestSeatGrade';

/**
 * 좌석 수정 요청 DTO
 */
export interface UpdateSeatRequest {
  /**
   * 구역
   * @minLength 0
   * @maxLength 50
   */
  section: string;
  /**
   * 좌석 열
   * @minLength 0
   * @maxLength 10
   */
  row: string;
  /**
   * 좌석 번호
   * @minimum 1
   */
  number: number;
  /** 좌석 등급 */
  seatGrade: UpdateSeatRequestSeatGrade;
  /**
   * 좌석배치도 X좌표
   * @minimum 0
   */
  positionX: number;
  /**
   * 좌석배치도 Y좌표
   * @minimum 0
   */
  positionY: number;
}
