/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateNoticeRequestCategory } from './updateNoticeRequestCategory';

/**
 * 공지사항 수정 요청
 */
export interface UpdateNoticeRequest {
  /** 공지사항 카테고리 (SYSTEM: 시스템 점검, BOOKING_NOTICE: 예매 유의사항, EVENT: 이벤트) */
  category: UpdateNoticeRequestCategory;
  /**
   * 제목
   * @minLength 0
   * @maxLength 255
   */
  title: string;
  /** 내용 */
  content: string;
  /** 정렬 순서 */
  displayOrder: number;
  /** 활성화 여부 */
  isActive: boolean;
}
