/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { VenueSeatCapacityResponseSeatGrade } from './venueSeatCapacityResponseSeatGrade';

/**
 * 공연장 등급별 좌석 수 응답 DTO
 */
export interface VenueSeatCapacityResponse {
  /** 좌석 수 ID */
  id: number;
  /** 공연장 ID */
  venueId: number;
  /** 좌석 등급 */
  seatGrade: VenueSeatCapacityResponseSeatGrade;
  /** 허용 좌석 수 */
  capacity: number;
}
