/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 공연장 정보 응답 DTO
 */
export interface VenueResponse {
  /** 공연장 ID */
  id: number;
  /** 공연장 이름 */
  name: string;
  /** 주소 */
  address?: string;
  /** 좌석 배치도 이미지 URL */
  seatingChartUrl?: string;
  /** 생성일시 */
  createdAt?: string;
  /** 수정일시 */
  updatedAt?: string;
}
