/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 공연장 정보 응답 DTO
 */
export interface VenueResponse {
  /** 공연장 ID */
  id: number;
  /** 공연장 이름 */
  name: string;
  /** 공연장 주소 */
  address?: string;
  /** 공연장 대표번호 */
  phoneNumber?: string;
  /** 좌석 배치도 존재 여부 */
  hasSeatingChart: boolean;
  /** 공연장 정보 생성일시 */
  createdAt?: string;
  /** 공연장 정보 수정일시 */
  updatedAt?: string;
}
