/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { SectionSeatsResponse } from './sectionSeatsResponse';

/**
 * 공연장 좌석 목록 응답 DTO (좌석배치도용)
 */
export interface VenueSeatMapResponse {
  /** 공연장 ID */
  venueId: number;
  /** 공연장 이름 */
  venueName: string;
  /** 총 좌석 수 */
  totalSeats: number;
  /** 구역별 좌석 목록 */
  sections: SectionSeatsResponse[];
}
