/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { VenueSeatCapacityRequestSeatGrade } from './venueSeatCapacityRequestSeatGrade';

/**
 * 공연장 등급별 좌석 수 요청 DTO
 */
export interface VenueSeatCapacityRequest {
  /** 좌석 등급 (VIP: VIP석, R: R석, S: S석, A: A석, B: B석) */
  seatGrade: VenueSeatCapacityRequestSeatGrade;
  /**
   * 허용 좌석 수
   * @minimum 0
   */
  capacity: number;
}
