/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { VenueSeatCapacityRequestSeatGrade } from './venueSeatCapacityRequestSeatGrade';

/**
 * 공연장 등급별 좌석 수 요청 DTO
 */
export interface VenueSeatCapacityRequest {
  /** 좌석 등급 */
  seatGrade: VenueSeatCapacityRequestSeatGrade;
  /**
   * 허용 좌석 수
   * @minimum 0
   */
  capacity: number;
}
