/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type { SeatGrade } from './seatGrade';

/**
 * 공연장 등급별 좌석 수 응답 DTO
 */
export interface VenueSeatCapacityResponse {
  /** 좌석 수 ID */
  id: number;
  /** 공연장 ID */
  venueId: number;
  seatGrade: SeatGrade;
  /** 허용 좌석 수 */
  capacity: number;
}
