/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 찜 목록 개별 공연 정보
 */
export interface WishlistResponse {
  /** 공연 ID */
  performanceId: number;
  /** 공연 제목 */
  title: string;
  /** 공연 메인 이미지 URL */
  mainImageUrl?: string;
  /** 공연장 명칭 */
  location: string;
  /** 가격 정보 (예: '70,000원~') */
  priceInfo: string;
}
