/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */

/**
 * 페이징 메타데이터
 */
export interface WishlistMetaResponse {
  /** 전체 아이템 수 */
  totalCount: number;
  /** 현재 페이지 (0-based) */
  currentPage: number;
  /** 한 페이지당 아이템 수 */
  pageSize: number;
  /** 전체 페이지 수 */
  totalPages: number;
  /** 다음 페이지 존재 여부 */
  hasNextPage: boolean;
  /** Cursor 기반일 경우 다음 시작점 (선택 사항) */
  nextCursor?: number;
}
