/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  AdminBookingResponse,
  BookingDetailResponse,
  BookingResponse,
  CancelBooking1Params
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 특정 예매 건의 상세 내역과 결제 정보를 조회합니다.

**권한: ADMIN**
 * @summary 예매 상세 조회
 */
export type getBookingDetail1Response200 = {
  data: BookingDetailResponse
  status: 200
}

export type getBookingDetail1Response404 = {
  data: BookingDetailResponse
  status: 404
}
    
export type getBookingDetail1ResponseSuccess = (getBookingDetail1Response200) & {
  headers: Headers;
};
export type getBookingDetail1ResponseError = (getBookingDetail1Response404) & {
  headers: Headers;
};

export type getBookingDetail1Response = (getBookingDetail1ResponseSuccess | getBookingDetail1ResponseError)

export const getGetBookingDetail1Url = (bookingId: string,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/bookings/${bookingId}`
}

export const getBookingDetail1 = async (bookingId: string, options?: RequestInit): Promise<getBookingDetail1Response> => {
  
  return orvalFetch<getBookingDetail1Response>(getGetBookingDetail1Url(bookingId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 관리자 권한으로 특정 예매를 강제 취소하고 환불 처리합니다.

**권한: ADMIN**

**[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
 * @summary 예매 강제 취소
 */
export type cancelBooking1Response200 = {
  data: BookingResponse
  status: 200
}

export type cancelBooking1Response404 = {
  data: BookingResponse
  status: 404
}
    
export type cancelBooking1ResponseSuccess = (cancelBooking1Response200) & {
  headers: Headers;
};
export type cancelBooking1ResponseError = (cancelBooking1Response404) & {
  headers: Headers;
};

export type cancelBooking1Response = (cancelBooking1ResponseSuccess | cancelBooking1ResponseError)

export const getCancelBooking1Url = (bookingId: string,
    params?: CancelBooking1Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/admin/bookings/${bookingId}?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/admin/bookings/${bookingId}`
}

export const cancelBooking1 = async (bookingId: string,
    params?: CancelBooking1Params, options?: RequestInit): Promise<cancelBooking1Response> => {
  
  return orvalFetch<cancelBooking1Response>(getCancelBooking1Url(bookingId,params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * 특정 공연 회차의 모든 예매 내역을 조회합니다.

**권한: ADMIN**
 * @summary 공연 회차별 예매 목록 조회
 */
export type getScheduleBookingsResponse200 = {
  data: AdminBookingResponse[]
  status: 200
}
    
export type getScheduleBookingsResponseSuccess = (getScheduleBookingsResponse200) & {
  headers: Headers;
};
;

export type getScheduleBookingsResponse = (getScheduleBookingsResponseSuccess)

export const getGetScheduleBookingsUrl = (scheduleId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/bookings/schedules/${scheduleId}`
}

export const getScheduleBookings = async (scheduleId: number, options?: RequestInit): Promise<getScheduleBookingsResponse> => {
  
  return orvalFetch<getScheduleBookingsResponse>(getGetScheduleBookingsUrl(scheduleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


