/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  AuditLogDetailResponse,
  AuditLogStatsResponse,
  GetAuditLogStatsParams,
  GetAuditLogsByUserParams,
  GetAuditLogsParams,
  PageAuditLogResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 다양한 필터를 사용하여 감사 로그 목록을 조회합니다.

**권한: ADMIN**
 * @summary 감사 로그 목록 조회
 */
export type getAuditLogsResponse200 = {
  data: PageAuditLogResponse
  status: 200
}
    
export type getAuditLogsResponseSuccess = (getAuditLogsResponse200) & {
  headers: Headers;
};
;

export type getAuditLogsResponse = (getAuditLogsResponseSuccess)

export const getGetAuditLogsUrl = (params: GetAuditLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/admin/audit-logs?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/admin/audit-logs`
}

export const getAuditLogs = async (params: GetAuditLogsParams, options?: RequestInit): Promise<getAuditLogsResponse> => {
  
  return orvalFetch<getAuditLogsResponse>(getGetAuditLogsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 특정 감사 로그의 상세 정보를 조회합니다. 요청 본문 등 추가 정보가 포함됩니다.

**권한: ADMIN**
 * @summary 감사 로그 상세 조회
 */
export type getAuditLogDetailResponse200 = {
  data: AuditLogDetailResponse
  status: 200
}
    
export type getAuditLogDetailResponseSuccess = (getAuditLogDetailResponse200) & {
  headers: Headers;
};
;

export type getAuditLogDetailResponse = (getAuditLogDetailResponseSuccess)

export const getGetAuditLogDetailUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/audit-logs/${id}`
}

export const getAuditLogDetail = async (id: number, options?: RequestInit): Promise<getAuditLogDetailResponse> => {
  
  return orvalFetch<getAuditLogDetailResponse>(getGetAuditLogDetailUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 특정 사용자의 모든 감사 로그를 조회합니다.

**권한: ADMIN**
 * @summary 특정 사용자의 감사 로그 조회
 */
export type getAuditLogsByUserResponse200 = {
  data: PageAuditLogResponse
  status: 200
}
    
export type getAuditLogsByUserResponseSuccess = (getAuditLogsByUserResponse200) & {
  headers: Headers;
};
;

export type getAuditLogsByUserResponse = (getAuditLogsByUserResponseSuccess)

export const getGetAuditLogsByUserUrl = (userId: number,
    params: GetAuditLogsByUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/admin/audit-logs/users/${userId}?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/admin/audit-logs/users/${userId}`
}

export const getAuditLogsByUser = async (userId: number,
    params: GetAuditLogsByUserParams, options?: RequestInit): Promise<getAuditLogsByUserResponse> => {
  
  return orvalFetch<getAuditLogsByUserResponse>(getGetAuditLogsByUserUrl(userId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 지정된 기간 동안의 감사 로그 통계를 조회합니다.

**권한: ADMIN**
 * @summary 감사 로그 통계
 */
export type getAuditLogStatsResponse200 = {
  data: AuditLogStatsResponse
  status: 200
}
    
export type getAuditLogStatsResponseSuccess = (getAuditLogStatsResponse200) & {
  headers: Headers;
};
;

export type getAuditLogStatsResponse = (getAuditLogStatsResponseSuccess)

export const getGetAuditLogStatsUrl = (params: GetAuditLogStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/admin/audit-logs/stats?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/admin/audit-logs/stats`
}

export const getAuditLogStats = async (params: GetAuditLogStatsParams, options?: RequestInit): Promise<getAuditLogStatsResponse> => {
  
  return orvalFetch<getAuditLogStatsResponse>(getGetAuditLogStatsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


