/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  AutocompleteParams,
  PerformanceAutocompleteResponse,
  PerformanceSearchListResponse,
  SearchParams
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 
            제목, 카테고리, 공연장 주소를 통합 검색하고 필터 및 정렬을 적용합니다. (권한: 누구나)
            
            **필터 상세**:
            - `status`: 판매 상태 (`PerformanceSearchStatus` - UPCOMING, ON_SALE, CLOSED)
            - `category`: 장르 (String - 뮤지컬, 콘서트, 연극 등)
            - `region`: 지역 (`Region` - SEOUL, GYEONGGI 등 17개 행정구역)
            - `sort`: 정렬 방식 (`PerformanceSearchSort` - BOOKING_COUNT, END_DATE_ASC, CREATED_AT_DESC)
        
 * @summary 공연 검색 및 필터링
 */
export type searchResponse200 = {
  data: PerformanceSearchListResponse
  status: 200
}
    
export type searchResponseSuccess = (searchResponse200) & {
  headers: Headers;
};
;

export type searchResponse = (searchResponseSuccess)

export const getSearchUrl = (params: SearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/performances/search?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/performances/search`
}

export const search = async (params: SearchParams, options?: RequestInit): Promise<searchResponse> => {
  
  return orvalFetch<searchResponse>(getSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 검색어 입력 시 최대 6개의 관련 공연을 추천합니다. (권한: 누구나)
 * @summary 검색 자동완성
 */
export type autocompleteResponse200 = {
  data: PerformanceAutocompleteResponse[]
  status: 200
}
    
export type autocompleteResponseSuccess = (autocompleteResponse200) & {
  headers: Headers;
};
;

export type autocompleteResponse = (autocompleteResponseSuccess)

export const getAutocompleteUrl = (params?: AutocompleteParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/performances/search/autocomplete?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/performances/search/autocomplete`
}

export const autocomplete = async (params?: AutocompleteParams, options?: RequestInit): Promise<autocompleteResponse> => {
  
  return orvalFetch<autocompleteResponse>(getAutocompleteUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


