/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type {
  BulkCreateSeatRequest,
  BulkCreateSeatResponse,
  CreateSeatRequest,
  ErrorResponse,
  SeatResponse,
  Unit,
  UpdateSeatRequest,
  VenueSeatMapResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 좌석 정보를 수정합니다.

**권한: ADMIN**
 * @summary 좌석 수정
 */
export type updateSeatResponse200 = {
  data: SeatResponse
  status: 200
}

export type updateSeatResponse400 = {
  data: ErrorResponse
  status: 400
}

export type updateSeatResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateSeatResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type updateSeatResponseSuccess = (updateSeatResponse200) & {
  headers: Headers;
};
export type updateSeatResponseError = (updateSeatResponse400 | updateSeatResponse404 | updateSeatResponse409) & {
  headers: Headers;
};

export type updateSeatResponse = (updateSeatResponseSuccess | updateSeatResponseError)

export const getUpdateSeatUrl = (venueId: number,
    seatId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/admin/venues/${venueId}/seats/${seatId}`
}

export const updateSeat = async (venueId: number,
    seatId: number,
    updateSeatRequest: UpdateSeatRequest, options?: RequestInit): Promise<updateSeatResponse> => {
  
  return orvalFetch<updateSeatResponse>(getUpdateSeatUrl(venueId,seatId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSeatRequest,)
  }
);}


/**
 * 좌석을 삭제합니다.

**권한: ADMIN**
 * @summary 좌석 삭제
 */
export type deleteSeatResponse204 = {
  data: Unit
  status: 204
}

export type deleteSeatResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type deleteSeatResponseSuccess = (deleteSeatResponse204) & {
  headers: Headers;
};
export type deleteSeatResponseError = (deleteSeatResponse404) & {
  headers: Headers;
};

export type deleteSeatResponse = (deleteSeatResponseSuccess | deleteSeatResponseError)

export const getDeleteSeatUrl = (venueId: number,
    seatId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/admin/venues/${venueId}/seats/${seatId}`
}

export const deleteSeat = async (venueId: number,
    seatId: number, options?: RequestInit): Promise<deleteSeatResponse> => {
  
  return orvalFetch<deleteSeatResponse>(getDeleteSeatUrl(venueId,seatId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * 공연장에 좌석을 생성합니다.

**권한: ADMIN**
 * @summary 좌석 단일 생성
 */
export type createSeatResponse201 = {
  data: SeatResponse
  status: 201
}

export type createSeatResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createSeatResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createSeatResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type createSeatResponseSuccess = (createSeatResponse201) & {
  headers: Headers;
};
export type createSeatResponseError = (createSeatResponse400 | createSeatResponse404 | createSeatResponse409) & {
  headers: Headers;
};

export type createSeatResponse = (createSeatResponseSuccess | createSeatResponseError)

export const getCreateSeatUrl = (venueId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/admin/venues/${venueId}/seats`
}

export const createSeat = async (venueId: number,
    createSeatRequest: CreateSeatRequest, options?: RequestInit): Promise<createSeatResponse> => {
  
  return orvalFetch<createSeatResponse>(getCreateSeatUrl(venueId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSeatRequest,)
  }
);}


/**
 * 공연장의 모든 좌석을 삭제합니다.

**권한: ADMIN**
 * @summary 공연장 전체 좌석 삭제
 */
export type deleteAllSeatsByVenueResponse204 = {
  data: Unit
  status: 204
}

export type deleteAllSeatsByVenueResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type deleteAllSeatsByVenueResponseSuccess = (deleteAllSeatsByVenueResponse204) & {
  headers: Headers;
};
export type deleteAllSeatsByVenueResponseError = (deleteAllSeatsByVenueResponse404) & {
  headers: Headers;
};

export type deleteAllSeatsByVenueResponse = (deleteAllSeatsByVenueResponseSuccess | deleteAllSeatsByVenueResponseError)

export const getDeleteAllSeatsByVenueUrl = (venueId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/admin/venues/${venueId}/seats`
}

export const deleteAllSeatsByVenue = async (venueId: number, options?: RequestInit): Promise<deleteAllSeatsByVenueResponse> => {
  
  return orvalFetch<deleteAllSeatsByVenueResponse>(getDeleteAllSeatsByVenueUrl(venueId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * 공연장에 좌석을 일괄 생성합니다.

**권한: ADMIN**
 * @summary 좌석 일괄 생성
 */
export type bulkCreateSeatsResponse201 = {
  data: BulkCreateSeatResponse
  status: 201
}

export type bulkCreateSeatsResponse400 = {
  data: ErrorResponse
  status: 400
}

export type bulkCreateSeatsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type bulkCreateSeatsResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type bulkCreateSeatsResponseSuccess = (bulkCreateSeatsResponse201) & {
  headers: Headers;
};
export type bulkCreateSeatsResponseError = (bulkCreateSeatsResponse400 | bulkCreateSeatsResponse404 | bulkCreateSeatsResponse409) & {
  headers: Headers;
};

export type bulkCreateSeatsResponse = (bulkCreateSeatsResponseSuccess | bulkCreateSeatsResponseError)

export const getBulkCreateSeatsUrl = (venueId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/admin/venues/${venueId}/seats/bulk`
}

export const bulkCreateSeats = async (venueId: number,
    bulkCreateSeatRequest: BulkCreateSeatRequest, options?: RequestInit): Promise<bulkCreateSeatsResponse> => {
  
  return orvalFetch<bulkCreateSeatsResponse>(getBulkCreateSeatsUrl(venueId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkCreateSeatRequest,)
  }
);}


/**
 * 공연장의 모든 좌석 정보를 조회합니다. (좌석배치도 렌더링용)
 * @summary 공연장 좌석 목록 조회
 */
export type getSeatsByVenueResponse200 = {
  data: VenueSeatMapResponse
  status: 200
}

export type getSeatsByVenueResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getSeatsByVenueResponseSuccess = (getSeatsByVenueResponse200) & {
  headers: Headers;
};
export type getSeatsByVenueResponseError = (getSeatsByVenueResponse404) & {
  headers: Headers;
};

export type getSeatsByVenueResponse = (getSeatsByVenueResponseSuccess | getSeatsByVenueResponseError)

export const getGetSeatsByVenueUrl = (venueId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/venues/${venueId}/seats`
}

export const getSeatsByVenue = async (venueId: number, options?: RequestInit): Promise<getSeatsByVenueResponse> => {
  
  return orvalFetch<getSeatsByVenueResponse>(getGetSeatsByVenueUrl(venueId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 특정 좌석의 상세 정보를 조회합니다.
 * @summary 좌석 상세 조회
 */
export type getSeatResponse200 = {
  data: SeatResponse
  status: 200
}

export type getSeatResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getSeatResponseSuccess = (getSeatResponse200) & {
  headers: Headers;
};
export type getSeatResponseError = (getSeatResponse404) & {
  headers: Headers;
};

export type getSeatResponse = (getSeatResponseSuccess | getSeatResponseError)

export const getGetSeatUrl = (venueId: number,
    seatId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/venues/${venueId}/seats/${seatId}`
}

export const getSeat = async (venueId: number,
    seatId: number, options?: RequestInit): Promise<getSeatResponse> => {
  
  return orvalFetch<getSeatResponse>(getGetSeatUrl(venueId,seatId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


