/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorResponse,
  PaymentCompleteRequest,
  PaymentCreateRequest,
  PaymentDetailResponse,
  PaymentResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 예매 정보를 기반으로 새로운 결제 요청을 생성합니다.

**권한: USER**
 * @summary 결제 요청 생성
 */
export type createPaymentResponse200 = {
  data: PaymentResponse
  status: 200
}

export type createPaymentResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type createPaymentResponseSuccess = (createPaymentResponse200) & {
  headers: Headers;
};
export type createPaymentResponseError = (createPaymentResponse404) & {
  headers: Headers;
};

export type createPaymentResponse = (createPaymentResponseSuccess | createPaymentResponseError)

export const getCreatePaymentUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/payments`
}

export const createPayment = async (paymentCreateRequest: PaymentCreateRequest, options?: RequestInit): Promise<createPaymentResponse> => {
  
  return orvalFetch<createPaymentResponse>(getCreatePaymentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      paymentCreateRequest,)
  }
);}


/**
 * PG사 결제 완료 후 승인 처리를 수행합니다.

**권한: USER**
 * @summary 결제 완료 승인
 */
export type completePaymentResponse200 = {
  data: PaymentResponse
  status: 200
}

export type completePaymentResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type completePaymentResponseSuccess = (completePaymentResponse200) & {
  headers: Headers;
};
export type completePaymentResponseError = (completePaymentResponse404) & {
  headers: Headers;
};

export type completePaymentResponse = (completePaymentResponseSuccess | completePaymentResponseError)

export const getCompletePaymentUrl = (id: string,) => {


  

  return `https://ticket-api.devhong.cc/api/payments/${id}/complete`
}

export const completePayment = async (id: string,
    paymentCompleteRequest: PaymentCompleteRequest, options?: RequestInit): Promise<completePaymentResponse> => {
  
  return orvalFetch<completePaymentResponse>(getCompletePaymentUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      paymentCompleteRequest,)
  }
);}


/**
 * 특정 결제 건의 상세 내역과 항목을 조회합니다.

**권한: USER**
 * @summary 결제 상세 조회
 */
export type getPaymentResponse200 = {
  data: PaymentDetailResponse
  status: 200
}
    
export type getPaymentResponseSuccess = (getPaymentResponse200) & {
  headers: Headers;
};
;

export type getPaymentResponse = (getPaymentResponseSuccess)

export const getGetPaymentUrl = (id: string,) => {


  

  return `https://ticket-api.devhong.cc/api/payments/${id}`
}

export const getPayment = async (id: string, options?: RequestInit): Promise<getPaymentResponse> => {
  
  return orvalFetch<getPaymentResponse>(getGetPaymentUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 로그인한 사용자의 전체 결제 내역을 조회합니다.

**권한: USER**
 * @summary 내 결제 목록 조회
 */
export type getMyPaymentsResponse200 = {
  data: PaymentResponse[]
  status: 200
}
    
export type getMyPaymentsResponseSuccess = (getMyPaymentsResponse200) & {
  headers: Headers;
};
;

export type getMyPaymentsResponse = (getMyPaymentsResponseSuccess)

export const getGetMyPaymentsUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/payments/me`
}

export const getMyPayments = async ( options?: RequestInit): Promise<getMyPaymentsResponse> => {
  
  return orvalFetch<getMyPaymentsResponse>(getGetMyPaymentsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


