/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorResponse,
  SeatingChartResponse,
  VenueResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 모든 공연장 목록을 조회합니다.

**권한: 누구나**
 * @summary 모든 공연장 조회
 */
export type getAllVenuesResponse200 = {
  data: VenueResponse[]
  status: 200
}
    
export type getAllVenuesResponseSuccess = (getAllVenuesResponse200) & {
  headers: Headers;
};
;

export type getAllVenuesResponse = (getAllVenuesResponseSuccess)

export const getGetAllVenuesUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/venues`
}

export const getAllVenues = async ( options?: RequestInit): Promise<getAllVenuesResponse> => {
  
  return orvalFetch<getAllVenuesResponse>(getGetAllVenuesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * ID로 특정 공연장의 정보를 조회합니다.

**권한: 누구나**
 * @summary 단일 공연장 조회
 */
export type getVenueResponse200 = {
  data: VenueResponse
  status: 200
}

export type getVenueResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getVenueResponseSuccess = (getVenueResponse200) & {
  headers: Headers;
};
export type getVenueResponseError = (getVenueResponse404) & {
  headers: Headers;
};

export type getVenueResponse = (getVenueResponseSuccess | getVenueResponseError)

export const getGetVenueUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/venues/${id}`
}

export const getVenue = async (id: number, options?: RequestInit): Promise<getVenueResponse> => {
  
  return orvalFetch<getVenueResponse>(getGetVenueUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 공연장의 좌석 배치도 JSON을 조회합니다.

**권한: 누구나**
 * @summary 좌석 배치도 조회
 */
export type getSeatingChartResponse200 = {
  data: SeatingChartResponse
  status: 200
}

export type getSeatingChartResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getSeatingChartResponseSuccess = (getSeatingChartResponse200) & {
  headers: Headers;
};
export type getSeatingChartResponseError = (getSeatingChartResponse404) & {
  headers: Headers;
};

export type getSeatingChartResponse = (getSeatingChartResponseSuccess | getSeatingChartResponseError)

export const getGetSeatingChartUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/venues/${id}/seating-chart`
}

export const getSeatingChart = async (id: number, options?: RequestInit): Promise<getSeatingChartResponse> => {
  
  return orvalFetch<getSeatingChartResponse>(getGetSeatingChartUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


