/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type {
  EmailVerificationRequest,
  ErrorResponse,
  LoginRequest,
  OtpConfirmationRequest,
  RefreshTokenRequest,
  SignupRequest,
  UserResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 이메일 인증(OTP 확인)이 완료된 후 새로운 사용자를 생성합니다.
 * @summary 회원가입
 */
export type signupResponse201 = {
  data: UserResponse
  status: 201
}

export type signupResponse400 = {
  data: ErrorResponse
  status: 400
}

export type signupResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type signupResponseSuccess = (signupResponse201) & {
  headers: Headers;
};
export type signupResponseError = (signupResponse400 | signupResponse409) & {
  headers: Headers;
};

export type signupResponse = (signupResponseSuccess | signupResponseError)

export const getSignupUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/auth/signup`
}

export const signup = async (signupRequest: SignupRequest, options?: RequestInit): Promise<signupResponse> => {
  
  return orvalFetch<signupResponse>(getSignupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signupRequest,)
  }
);}


/**
 * 리프레시 토큰으로 새로운 액세스 토큰을 발급받습니다.
 * @summary 토큰 갱신
 */
export type refreshResponse200 = {
  data: void
  status: 200
}

export type refreshResponse401 = {
  data: ErrorResponse
  status: 401
}
    
export type refreshResponseSuccess = (refreshResponse200) & {
  headers: Headers;
};
export type refreshResponseError = (refreshResponse401) & {
  headers: Headers;
};

export type refreshResponse = (refreshResponseSuccess | refreshResponseError)

export const getRefreshUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/auth/refresh`
}

export const refresh = async (refreshTokenRequest: RefreshTokenRequest, options?: RequestInit): Promise<refreshResponse> => {
  
  return orvalFetch<refreshResponse>(getRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshTokenRequest,)
  }
);}


/**
 * 사용자 세션을 종료하고 인증 쿠키를 삭제합니다.
 * @summary 로그아웃
 */
export type logoutResponse200 = {
  data: void
  status: 200
}
    
export type logoutResponseSuccess = (logoutResponse200) & {
  headers: Headers;
};
;

export type logoutResponse = (logoutResponseSuccess)

export const getLogoutUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/auth/logout`
}

export const logout = async ( options?: RequestInit): Promise<logoutResponse> => {
  
  return orvalFetch<logoutResponse>(getLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * 이메일과 비밀번호로 로그인하고 JWT 토큰을 발급받습니다.
 * @summary 로그인
 */
export type loginResponse200 = {
  data: UserResponse
  status: 200
}

export type loginResponse401 = {
  data: ErrorResponse
  status: 401
}
    
export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse401) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/auth/login`
}

export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginResponse> => {
  
  return orvalFetch<loginResponse>(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}


/**
 * 회원가입을 위한 이메일 인증번호(OTP)를 요청합니다. 지정된 이메일 주소로 OTP가 발송됩니다.
 * @summary 이메일 인증 요청 (OTP 발송)
 */
export type requestEmailVerificationResponse200 = {
  data: void
  status: 200
}

export type requestEmailVerificationResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type requestEmailVerificationResponseSuccess = (requestEmailVerificationResponse200) & {
  headers: Headers;
};
export type requestEmailVerificationResponseError = (requestEmailVerificationResponse409) & {
  headers: Headers;
};

export type requestEmailVerificationResponse = (requestEmailVerificationResponseSuccess | requestEmailVerificationResponseError)

export const getRequestEmailVerificationUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/auth/email-verification/request`
}

export const requestEmailVerification = async (emailVerificationRequest: EmailVerificationRequest, options?: RequestInit): Promise<requestEmailVerificationResponse> => {
  
  return orvalFetch<requestEmailVerificationResponse>(getRequestEmailVerificationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailVerificationRequest,)
  }
);}


/**
 * 이메일로 발송된 6자리 OTP를 확인합니다.
 * @summary OTP 확인
 */
export type confirmOtpResponse200 = {
  data: void
  status: 200
}

export type confirmOtpResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type confirmOtpResponseSuccess = (confirmOtpResponse200) & {
  headers: Headers;
};
export type confirmOtpResponseError = (confirmOtpResponse400) & {
  headers: Headers;
};

export type confirmOtpResponse = (confirmOtpResponseSuccess | confirmOtpResponseError)

export const getConfirmOtpUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/auth/confirm-otp`
}

export const confirmOtp = async (otpConfirmationRequest: OtpConfirmationRequest, options?: RequestInit): Promise<confirmOtpResponse> => {
  
  return orvalFetch<confirmOtpResponse>(getConfirmOtpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      otpConfirmationRequest,)
  }
);}


/**
 * 현재 로그인된 사용자 정보를 조회합니다.
 * @summary 내 정보 조회
 */
export type meResponse200 = {
  data: UserResponse
  status: 200
}

export type meResponse401 = {
  data: ErrorResponse
  status: 401
}

export type meResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type meResponseSuccess = (meResponse200) & {
  headers: Headers;
};
export type meResponseError = (meResponse401 | meResponse404) & {
  headers: Headers;
};

export type meResponse = (meResponseSuccess | meResponseError)

export const getMeUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/auth/me`
}

export const me = async ( options?: RequestInit): Promise<meResponse> => {
  
  return orvalFetch<meResponse>(getMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


