/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  CompanyRequest,
  CompanyResponse,
  ErrorResponse,
  Unit
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * ID로 특정 판매자 정보를 조회합니다.

**권한: ADMIN**
 * @summary 단일 판매자 조회
 */
export type getCompanyResponse200 = {
  data: CompanyResponse
  status: 200
}

export type getCompanyResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getCompanyResponseSuccess = (getCompanyResponse200) & {
  headers: Headers;
};
export type getCompanyResponseError = (getCompanyResponse404) & {
  headers: Headers;
};

export type getCompanyResponse = (getCompanyResponseSuccess | getCompanyResponseError)

export const getGetCompanyUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/companies/${id}`
}

export const getCompany = async (id: number, options?: RequestInit): Promise<getCompanyResponse> => {
  
  return orvalFetch<getCompanyResponse>(getGetCompanyUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 특정 판매자 정보를 수정합니다.

**권한: ADMIN**
 * @summary 판매자 정보 수정
 */
export type updateCompanyResponse200 = {
  data: CompanyResponse
  status: 200
}

export type updateCompanyResponse400 = {
  data: ErrorResponse
  status: 400
}

export type updateCompanyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateCompanyResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type updateCompanyResponseSuccess = (updateCompanyResponse200) & {
  headers: Headers;
};
export type updateCompanyResponseError = (updateCompanyResponse400 | updateCompanyResponse404 | updateCompanyResponse409) & {
  headers: Headers;
};

export type updateCompanyResponse = (updateCompanyResponseSuccess | updateCompanyResponseError)

export const getUpdateCompanyUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/companies/${id}`
}

export const updateCompany = async (id: number,
    companyRequest: CompanyRequest, options?: RequestInit): Promise<updateCompanyResponse> => {
  
  return orvalFetch<updateCompanyResponse>(getUpdateCompanyUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      companyRequest,)
  }
);}


/**
 * 특정 판매자를 삭제합니다.

**권한: ADMIN**
 * @summary 판매자 삭제
 */
export type deleteCompanyResponse204 = {
  data: Unit
  status: 204
}

export type deleteCompanyResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type deleteCompanyResponseSuccess = (deleteCompanyResponse204) & {
  headers: Headers;
};
export type deleteCompanyResponseError = (deleteCompanyResponse404) & {
  headers: Headers;
};

export type deleteCompanyResponse = (deleteCompanyResponseSuccess | deleteCompanyResponseError)

export const getDeleteCompanyUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/companies/${id}`
}

export const deleteCompany = async (id: number, options?: RequestInit): Promise<deleteCompanyResponse> => {
  
  return orvalFetch<deleteCompanyResponse>(getDeleteCompanyUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * 모든 판매자 목록을 조회합니다.

**권한: ADMIN**
 * @summary 모든 판매자 조회
 */
export type getAllCompaniesResponse200 = {
  data: CompanyResponse[]
  status: 200
}
    
export type getAllCompaniesResponseSuccess = (getAllCompaniesResponse200) & {
  headers: Headers;
};
;

export type getAllCompaniesResponse = (getAllCompaniesResponseSuccess)

export const getGetAllCompaniesUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/admin/companies`
}

export const getAllCompanies = async ( options?: RequestInit): Promise<getAllCompaniesResponse> => {
  
  return orvalFetch<getAllCompaniesResponse>(getGetAllCompaniesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 새로운 판매자 정보를 생성합니다.

**권한: ADMIN**
 * @summary 판매자 생성
 */
export type createCompanyResponse201 = {
  data: CompanyResponse
  status: 201
}

export type createCompanyResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createCompanyResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type createCompanyResponseSuccess = (createCompanyResponse201) & {
  headers: Headers;
};
export type createCompanyResponseError = (createCompanyResponse400 | createCompanyResponse409) & {
  headers: Headers;
};

export type createCompanyResponse = (createCompanyResponseSuccess | createCompanyResponseError)

export const getCreateCompanyUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/admin/companies`
}

export const createCompany = async (companyRequest: CompanyRequest, options?: RequestInit): Promise<createCompanyResponse> => {
  
  return orvalFetch<createCompanyResponse>(getCreateCompanyUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      companyRequest,)
  }
);}


