/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetAllEnums200
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 모든 공통 Enum을 한번에 조회합니다. 앱 초기화 시 호출하여 캐싱해서 사용하세요.

**권한: 누구나**
 * @summary 전체 Enum 목록
 */
export type getAllEnumsResponse200 = {
  data: GetAllEnums200
  status: 200
}
    
export type getAllEnumsResponseSuccess = (getAllEnumsResponse200) & {
  headers: Headers;
};
;

export type getAllEnumsResponse = (getAllEnumsResponseSuccess)

export const getGetAllEnumsUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/enums`
}

export const getAllEnums = async ( options?: RequestInit): Promise<getAllEnumsResponse> => {
  
  return orvalFetch<getAllEnumsResponse>(getGetAllEnumsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


