/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateNoticeRequest,
  NoticeGroupResponse,
  NoticeResponse,
  NoticeStatusRequest,
  UpdateNoticeRequest
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 특정 공지사항의 상세 정보를 조회합니다.

**권한: ADMIN**
 * @summary [관리자] 공지사항 상세 조회
 */
export type getNoticeByIdResponse200 = {
  data: NoticeResponse
  status: 200
}
    
export type getNoticeByIdResponseSuccess = (getNoticeByIdResponse200) & {
  headers: Headers;
};
;

export type getNoticeByIdResponse = (getNoticeByIdResponseSuccess)

export const getGetNoticeByIdUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/notices/${id}`
}

export const getNoticeById = async (id: number, options?: RequestInit): Promise<getNoticeByIdResponse> => {
  
  return orvalFetch<getNoticeByIdResponse>(getGetNoticeByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 기존 공지사항을 수정합니다.

**권한: ADMIN**

**[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
 * @summary [관리자] 공지사항 수정
 */
export type updateNoticeResponse200 = {
  data: NoticeResponse
  status: 200
}
    
export type updateNoticeResponseSuccess = (updateNoticeResponse200) & {
  headers: Headers;
};
;

export type updateNoticeResponse = (updateNoticeResponseSuccess)

export const getUpdateNoticeUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/notices/${id}`
}

export const updateNotice = async (id: number,
    updateNoticeRequest: UpdateNoticeRequest, options?: RequestInit): Promise<updateNoticeResponse> => {
  
  return orvalFetch<updateNoticeResponse>(getUpdateNoticeUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateNoticeRequest,)
  }
);}


/**
 * 공지사항을 삭제합니다.

**권한: ADMIN**

**[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
 * @summary [관리자] 공지사항 삭제
 */
export type deleteNoticeResponse200 = {
  data: void
  status: 200
}
    
export type deleteNoticeResponseSuccess = (deleteNoticeResponse200) & {
  headers: Headers;
};
;

export type deleteNoticeResponse = (deleteNoticeResponseSuccess)

export const getDeleteNoticeUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/notices/${id}`
}

export const deleteNotice = async (id: number, options?: RequestInit): Promise<deleteNoticeResponse> => {
  
  return orvalFetch<deleteNoticeResponse>(getDeleteNoticeUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * 비활성화된 항목을 포함한 전체 목록을 조회합니다.

**권한: ADMIN**
 * @summary [관리자] 전체 공지사항 목록 조회
 */
export type getAllNoticesResponse200 = {
  data: NoticeResponse[]
  status: 200
}
    
export type getAllNoticesResponseSuccess = (getAllNoticesResponse200) & {
  headers: Headers;
};
;

export type getAllNoticesResponse = (getAllNoticesResponseSuccess)

export const getGetAllNoticesUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/admin/notices`
}

export const getAllNotices = async ( options?: RequestInit): Promise<getAllNoticesResponse> => {
  
  return orvalFetch<getAllNoticesResponse>(getGetAllNoticesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 새로운 공지사항을 생성합니다.

**권한: ADMIN**

**[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
 * @summary [관리자] 공지사항 생성
 */
export type createNoticeResponse200 = {
  data: NoticeResponse
  status: 200
}
    
export type createNoticeResponseSuccess = (createNoticeResponse200) & {
  headers: Headers;
};
;

export type createNoticeResponse = (createNoticeResponseSuccess)

export const getCreateNoticeUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/admin/notices`
}

export const createNotice = async (createNoticeRequest: CreateNoticeRequest, options?: RequestInit): Promise<createNoticeResponse> => {
  
  return orvalFetch<createNoticeResponse>(getCreateNoticeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createNoticeRequest,)
  }
);}


/**
 * 공지사항의 활성화 상태를 수정합니다. `isActive=true`로 전환 시 동일 카테고리의 다른 공지사항은 자동으로 비활성화됩니다.

**권한: ADMIN**

**[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
 * @summary [관리자] 공지사항 상태 수정
 */
export type updateNoticeStatusResponse200 = {
  data: NoticeResponse
  status: 200
}
    
export type updateNoticeStatusResponseSuccess = (updateNoticeStatusResponse200) & {
  headers: Headers;
};
;

export type updateNoticeStatusResponse = (updateNoticeStatusResponseSuccess)

export const getUpdateNoticeStatusUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/notices/${id}/status`
}

export const updateNoticeStatus = async (id: number,
    noticeStatusRequest: NoticeStatusRequest, options?: RequestInit): Promise<updateNoticeStatusResponse> => {
  
  return orvalFetch<updateNoticeStatusResponse>(getUpdateNoticeStatusUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      noticeStatusRequest,)
  }
);}


/**
 * 비활성화된 항목을 포함하여 카테고리별로 그룹화된 목록을 조회합니다.

**권한: ADMIN**
 * @summary [관리자] 카테고리별 공지사항 목록 조회
 */
export type getAllNoticesGroupedResponse200 = {
  data: NoticeGroupResponse[]
  status: 200
}
    
export type getAllNoticesGroupedResponseSuccess = (getAllNoticesGroupedResponse200) & {
  headers: Headers;
};
;

export type getAllNoticesGroupedResponse = (getAllNoticesGroupedResponseSuccess)

export const getGetAllNoticesGroupedUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/admin/notices/grouped`
}

export const getAllNoticesGrouped = async ( options?: RequestInit): Promise<getAllNoticesGroupedResponse> => {
  
  return orvalFetch<getAllNoticesGroupedResponse>(getGetAllNoticesGroupedUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


