/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type {
  SeatStatusEvent
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 
            Server-Sent Events를 통해 실시간 좌석 상태 변경을 수신합니다.

            **사용 방법:**
            ```javascript
            const eventSource = new EventSource('/api/schedules/1/seats/events');

            eventSource.onmessage = (event) => {
                const data = JSON.parse(event.data);
                if (!data.isHeartbeat) {
                    // 좌석 상태 업데이트 처리
                    console.log('Seat', data.scheduleSeatId, 'changed to', data.status);
                }
            };

            eventSource.onerror = (error) => {
                console.error('SSE connection error:', error);
                eventSource.close();
            };
            ```

            **이벤트 데이터 형식:**
            - `scheduleSeatId`: 좌석 ID (-1이면 하트비트)
            - `status`: 새 상태 (AVAILABLE, HELD, RESERVED)
            - `timestamp`: 이벤트 발생 시간
            - `isHeartbeat`: 하트비트 여부 (30초마다 전송)
        
 * @summary 좌석 상태 실시간 업데이트 (SSE)
 */
export type streamSeatEventsResponse200 = {
  data: SeatStatusEvent[]
  status: 200
}
    
export type streamSeatEventsResponseSuccess = (streamSeatEventsResponse200) & {
  headers: Headers;
};
;

export type streamSeatEventsResponse = (streamSeatEventsResponseSuccess)

export const getStreamSeatEventsUrl = (scheduleId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seats/events`
}

export const streamSeatEvents = async (scheduleId: number, options?: RequestInit): Promise<streamSeatEventsResponse> => {
  
  return orvalFetch<streamSeatEventsResponse>(getStreamSeatEventsUrl(scheduleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


