/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateScheduleTicketStockRequest,
  ErrorResponse,
  ScheduleTicketStockResponse,
  Unit,
  UpdateScheduleTicketStockRequest
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 회차별 좌석등급 재고를 조회합니다.
 * @summary 재고 조회
 */
export type getStockResponse200 = {
  data: ScheduleTicketStockResponse
  status: 200
}

export type getStockResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getStockResponseSuccess = (getStockResponse200) & {
  headers: Headers;
};
export type getStockResponseError = (getStockResponse404) & {
  headers: Headers;
};

export type getStockResponse = (getStockResponseSuccess | getStockResponseError)

export const getGetStockUrl = (id: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedule-ticket-stocks/${id}`
}

export const getStock = async (id: number, options?: RequestInit): Promise<getStockResponse> => {
  
  return orvalFetch<getStockResponse>(getGetStockUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 회차별 좌석등급 재고를 수정합니다.

**권한: ADMIN**
 * @summary 재고 수정
 */
export type updateStockResponse200 = {
  data: ScheduleTicketStockResponse
  status: 200
}

export type updateStockResponse400 = {
  data: ErrorResponse
  status: 400
}

export type updateStockResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type updateStockResponseSuccess = (updateStockResponse200) & {
  headers: Headers;
};
export type updateStockResponseError = (updateStockResponse400 | updateStockResponse404) & {
  headers: Headers;
};

export type updateStockResponse = (updateStockResponseSuccess | updateStockResponseError)

export const getUpdateStockUrl = (id: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedule-ticket-stocks/${id}`
}

export const updateStock = async (id: number,
    updateScheduleTicketStockRequest: UpdateScheduleTicketStockRequest, options?: RequestInit): Promise<updateStockResponse> => {
  
  return orvalFetch<updateStockResponse>(getUpdateStockUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateScheduleTicketStockRequest,)
  }
);}


/**
 * 회차별 좌석등급 재고를 삭제합니다.

**권한: ADMIN**
 * @summary 재고 삭제
 */
export type deleteStockResponse204 = {
  data: Unit
  status: 204
}

export type deleteStockResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type deleteStockResponseSuccess = (deleteStockResponse204) & {
  headers: Headers;
};
export type deleteStockResponseError = (deleteStockResponse404) & {
  headers: Headers;
};

export type deleteStockResponse = (deleteStockResponseSuccess | deleteStockResponseError)

export const getDeleteStockUrl = (id: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedule-ticket-stocks/${id}`
}

export const deleteStock = async (id: number, options?: RequestInit): Promise<deleteStockResponse> => {
  
  return orvalFetch<deleteStockResponse>(getDeleteStockUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * 회차별 좌석등급 재고를 생성합니다.

**권한: ADMIN**
 * @summary 재고 생성
 */
export type createStockResponse201 = {
  data: ScheduleTicketStockResponse
  status: 201
}

export type createStockResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createStockResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type createStockResponseSuccess = (createStockResponse201) & {
  headers: Headers;
};
export type createStockResponseError = (createStockResponse400 | createStockResponse404) & {
  headers: Headers;
};

export type createStockResponse = (createStockResponseSuccess | createStockResponseError)

export const getCreateStockUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/schedule-ticket-stocks`
}

export const createStock = async (createScheduleTicketStockRequest: CreateScheduleTicketStockRequest, options?: RequestInit): Promise<createStockResponse> => {
  
  return orvalFetch<createStockResponse>(getCreateStockUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createScheduleTicketStockRequest,)
  }
);}


/**
 * 특정 회차의 모든 좌석등급 재고를 조회합니다.
 * @summary 회차별 재고 목록 조회
 */
export type getStocksByScheduleResponse200 = {
  data: ScheduleTicketStockResponse[]
  status: 200
}
    
export type getStocksByScheduleResponseSuccess = (getStocksByScheduleResponse200) & {
  headers: Headers;
};
;

export type getStocksByScheduleResponse = (getStocksByScheduleResponseSuccess)

export const getGetStocksByScheduleUrl = (scheduleId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedule-ticket-stocks/schedule/${scheduleId}`
}

export const getStocksBySchedule = async (scheduleId: number, options?: RequestInit): Promise<getStocksByScheduleResponse> => {
  
  return orvalFetch<getStocksByScheduleResponse>(getGetStocksByScheduleUrl(scheduleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 특정 공연의 모든 회차/좌석등급 재고를 조회합니다.
 * @summary 공연별 재고 목록 조회
 */
export type getStocksByPerformanceResponse200 = {
  data: ScheduleTicketStockResponse[]
  status: 200
}
    
export type getStocksByPerformanceResponseSuccess = (getStocksByPerformanceResponse200) & {
  headers: Headers;
};
;

export type getStocksByPerformanceResponse = (getStocksByPerformanceResponseSuccess)

export const getGetStocksByPerformanceUrl = (performanceId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedule-ticket-stocks/performance/${performanceId}`
}

export const getStocksByPerformance = async (performanceId: number, options?: RequestInit): Promise<getStocksByPerformanceResponse> => {
  
  return orvalFetch<getStocksByPerformanceResponse>(getGetStocksByPerformanceUrl(performanceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


