/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  DailySalesStats,
  DiscountStats,
  GetDailySalesParams,
  GetDiscountStatsParams,
  GetPaymentMethodStatsParams,
  PaymentMethodStats,
  PerformanceSalesStats
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * @summary 공연별 매출 통계 조회
 */
export type getPerformanceSalesResponse200 = {
  data: PerformanceSalesStats[]
  status: 200
}
    
export type getPerformanceSalesResponseSuccess = (getPerformanceSalesResponse200) & {
  headers: Headers;
};
;

export type getPerformanceSalesResponse = (getPerformanceSalesResponseSuccess)

export const getGetPerformanceSalesUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/stats/performance/${id}`
}

export const getPerformanceSales = async (id: number, options?: RequestInit): Promise<getPerformanceSalesResponse> => {
  
  return orvalFetch<getPerformanceSalesResponse>(getGetPerformanceSalesUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary 결제 수단별 통계 조회
 */
export type getPaymentMethodStatsResponse200 = {
  data: PaymentMethodStats[]
  status: 200
}
    
export type getPaymentMethodStatsResponseSuccess = (getPaymentMethodStatsResponse200) & {
  headers: Headers;
};
;

export type getPaymentMethodStatsResponse = (getPaymentMethodStatsResponseSuccess)

export const getGetPaymentMethodStatsUrl = (params: GetPaymentMethodStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/admin/stats/payment-methods?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/admin/stats/payment-methods`
}

export const getPaymentMethodStats = async (params: GetPaymentMethodStatsParams, options?: RequestInit): Promise<getPaymentMethodStatsResponse> => {
  
  return orvalFetch<getPaymentMethodStatsResponse>(getGetPaymentMethodStatsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary 할인 종류별 통계 조회
 */
export type getDiscountStatsResponse200 = {
  data: DiscountStats[]
  status: 200
}
    
export type getDiscountStatsResponseSuccess = (getDiscountStatsResponse200) & {
  headers: Headers;
};
;

export type getDiscountStatsResponse = (getDiscountStatsResponseSuccess)

export const getGetDiscountStatsUrl = (params: GetDiscountStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/admin/stats/discounts?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/admin/stats/discounts`
}

export const getDiscountStats = async (params: GetDiscountStatsParams, options?: RequestInit): Promise<getDiscountStatsResponse> => {
  
  return orvalFetch<getDiscountStatsResponse>(getGetDiscountStatsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary 일별 매출 통계 조회
 */
export type getDailySalesResponse200 = {
  data: DailySalesStats
  status: 200
}
    
export type getDailySalesResponseSuccess = (getDailySalesResponse200) & {
  headers: Headers;
};
;

export type getDailySalesResponse = (getDailySalesResponseSuccess)

export const getGetDailySalesUrl = (params: GetDailySalesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/admin/stats/daily?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/admin/stats/daily`
}

export const getDailySales = async (params: GetDailySalesParams, options?: RequestInit): Promise<getDailySalesResponse> => {
  
  return orvalFetch<getDailySalesResponse>(getGetDailySalesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


