/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddHomeTagRequest,
  ErrorResponse,
  PerformanceHomeTagResponse,
  SectionMetadataResponse,
  TagPerformanceResponse,
  Unit,
  UpdateDisplayOrderRequest
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 특정 공연에 등록된 모든 홈 태그를 조회합니다.

**권한: ADMIN**
 * @summary 공연의 홈 태그 목록 조회
 */
export type getHomeTagsByPerformanceResponse200 = {
  data: PerformanceHomeTagResponse[]
  status: 200
}

export type getHomeTagsByPerformanceResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getHomeTagsByPerformanceResponseSuccess = (getHomeTagsByPerformanceResponse200) & {
  headers: Headers;
};
export type getHomeTagsByPerformanceResponseError = (getHomeTagsByPerformanceResponse404) & {
  headers: Headers;
};

export type getHomeTagsByPerformanceResponse = (getHomeTagsByPerformanceResponseSuccess | getHomeTagsByPerformanceResponseError)

export const getGetHomeTagsByPerformanceUrl = (performanceId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/performances/${performanceId}/home-tags`
}

export const getHomeTagsByPerformance = async (performanceId: number, options?: RequestInit): Promise<getHomeTagsByPerformanceResponse> => {
  
  return orvalFetch<getHomeTagsByPerformanceResponse>(getGetHomeTagsByPerformanceUrl(performanceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 
공연을 홈 화면의 특정 태그에 추가합니다.

**권한: ADMIN**

**주의사항:**
- 지역 태그(REGION_*)는 수동 추가 불가 (공연장 주소 기반 자동 태깅)
- 동일 태그 중복 추가 불가
        
 * @summary 공연에 홈 태그 추가
 */
export type addHomeTagResponse201 = {
  data: PerformanceHomeTagResponse
  status: 201
}

export type addHomeTagResponse400 = {
  data: ErrorResponse
  status: 400
}

export type addHomeTagResponse404 = {
  data: ErrorResponse
  status: 404
}

export type addHomeTagResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type addHomeTagResponseSuccess = (addHomeTagResponse201) & {
  headers: Headers;
};
export type addHomeTagResponseError = (addHomeTagResponse400 | addHomeTagResponse404 | addHomeTagResponse409) & {
  headers: Headers;
};

export type addHomeTagResponse = (addHomeTagResponseSuccess | addHomeTagResponseError)

export const getAddHomeTagUrl = (performanceId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/performances/${performanceId}/home-tags`
}

export const addHomeTag = async (performanceId: number,
    addHomeTagRequest: AddHomeTagRequest, options?: RequestInit): Promise<addHomeTagResponse> => {
  
  return orvalFetch<addHomeTagResponse>(getAddHomeTagUrl(performanceId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addHomeTagRequest,)
  }
);}


/**
 * 태그 내 공연들의 노출 순서를 일괄 변경합니다.

**권한: ADMIN**
 * @summary 태그 내 공연 순서 변경
 */
export type updateDisplayOrderResponse200 = {
  data: Unit
  status: 200
}

export type updateDisplayOrderResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type updateDisplayOrderResponseSuccess = (updateDisplayOrderResponse200) & {
  headers: Headers;
};
export type updateDisplayOrderResponseError = (updateDisplayOrderResponse404) & {
  headers: Headers;
};

export type updateDisplayOrderResponse = (updateDisplayOrderResponseSuccess | updateDisplayOrderResponseError)

export const getUpdateDisplayOrderUrl = (tag: 'WEEKLY_OPEN' | 'MUSICAL' | 'CONCERT' | 'THEATER' | 'EXHIBITION' | 'DATE_MUSICAL' | 'DATE_THEATER' | 'DATE_CLASSIC' | 'DATE_EXHIBITION' | 'LIMITED_SALE' | 'WITH_KIDS' | 'DAEHAKRO' | 'REGION_SEOUL' | 'REGION_GYEONGGI' | 'REGION_BUSAN' | 'REGION_DAEGU' | 'REGION_DAEJEON' | 'REGION_NATIONWIDE',) => {


  

  return `https://ticket-api.devhong.cc/api/admin/home-tags/${tag}/performances/order`
}

export const updateDisplayOrder = async (tag: 'WEEKLY_OPEN' | 'MUSICAL' | 'CONCERT' | 'THEATER' | 'EXHIBITION' | 'DATE_MUSICAL' | 'DATE_THEATER' | 'DATE_CLASSIC' | 'DATE_EXHIBITION' | 'LIMITED_SALE' | 'WITH_KIDS' | 'DAEHAKRO' | 'REGION_SEOUL' | 'REGION_GYEONGGI' | 'REGION_BUSAN' | 'REGION_DAEGU' | 'REGION_DAEJEON' | 'REGION_NATIONWIDE',
    updateDisplayOrderRequest: UpdateDisplayOrderRequest, options?: RequestInit): Promise<updateDisplayOrderResponse> => {
  
  return orvalFetch<updateDisplayOrderResponse>(getUpdateDisplayOrderUrl(tag),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateDisplayOrderRequest,)
  }
);}


/**
 * 홈 화면의 모든 섹션과 태그 목록을 조회합니다.

**권한: ADMIN**
 * @summary 섹션/태그 메타 정보 조회
 */
export type getSectionsMetadataResponse200 = {
  data: SectionMetadataResponse[]
  status: 200
}
    
export type getSectionsMetadataResponseSuccess = (getSectionsMetadataResponse200) & {
  headers: Headers;
};
;

export type getSectionsMetadataResponse = (getSectionsMetadataResponseSuccess)

export const getGetSectionsMetadataUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/admin/home/sections/metadata`
}

export const getSectionsMetadata = async ( options?: RequestInit): Promise<getSectionsMetadataResponse> => {
  
  return orvalFetch<getSectionsMetadataResponse>(getGetSectionsMetadataUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 특정 태그에 등록된 모든 공연을 순서대로 조회합니다.

**권한: ADMIN**
 * @summary 태그별 공연 목록 조회
 */
export type getPerformancesByTag1Response200 = {
  data: TagPerformanceResponse[]
  status: 200
}
    
export type getPerformancesByTag1ResponseSuccess = (getPerformancesByTag1Response200) & {
  headers: Headers;
};
;

export type getPerformancesByTag1Response = (getPerformancesByTag1ResponseSuccess)

export const getGetPerformancesByTag1Url = (tag: 'WEEKLY_OPEN' | 'MUSICAL' | 'CONCERT' | 'THEATER' | 'EXHIBITION' | 'DATE_MUSICAL' | 'DATE_THEATER' | 'DATE_CLASSIC' | 'DATE_EXHIBITION' | 'LIMITED_SALE' | 'WITH_KIDS' | 'DAEHAKRO' | 'REGION_SEOUL' | 'REGION_GYEONGGI' | 'REGION_BUSAN' | 'REGION_DAEGU' | 'REGION_DAEJEON' | 'REGION_NATIONWIDE',) => {


  

  return `https://ticket-api.devhong.cc/api/admin/home-tags/${tag}/performances`
}

export const getPerformancesByTag1 = async (tag: 'WEEKLY_OPEN' | 'MUSICAL' | 'CONCERT' | 'THEATER' | 'EXHIBITION' | 'DATE_MUSICAL' | 'DATE_THEATER' | 'DATE_CLASSIC' | 'DATE_EXHIBITION' | 'LIMITED_SALE' | 'WITH_KIDS' | 'DAEHAKRO' | 'REGION_SEOUL' | 'REGION_GYEONGGI' | 'REGION_BUSAN' | 'REGION_DAEGU' | 'REGION_DAEJEON' | 'REGION_NATIONWIDE', options?: RequestInit): Promise<getPerformancesByTag1Response> => {
  
  return orvalFetch<getPerformancesByTag1Response>(getGetPerformancesByTag1Url(tag),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 공연에서 특정 홈 태그를 제거합니다.

**권한: ADMIN**
 * @summary 공연의 홈 태그 삭제
 */
export type removeHomeTagResponse204 = {
  data: Unit
  status: 204
}

export type removeHomeTagResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type removeHomeTagResponseSuccess = (removeHomeTagResponse204) & {
  headers: Headers;
};
export type removeHomeTagResponseError = (removeHomeTagResponse404) & {
  headers: Headers;
};

export type removeHomeTagResponse = (removeHomeTagResponseSuccess | removeHomeTagResponseError)

export const getRemoveHomeTagUrl = (performanceId: number,
    tag: 'WEEKLY_OPEN' | 'MUSICAL' | 'CONCERT' | 'THEATER' | 'EXHIBITION' | 'DATE_MUSICAL' | 'DATE_THEATER' | 'DATE_CLASSIC' | 'DATE_EXHIBITION' | 'LIMITED_SALE' | 'WITH_KIDS' | 'DAEHAKRO' | 'REGION_SEOUL' | 'REGION_GYEONGGI' | 'REGION_BUSAN' | 'REGION_DAEGU' | 'REGION_DAEJEON' | 'REGION_NATIONWIDE',) => {


  

  return `https://ticket-api.devhong.cc/api/admin/performances/${performanceId}/home-tags/${tag}`
}

export const removeHomeTag = async (performanceId: number,
    tag: 'WEEKLY_OPEN' | 'MUSICAL' | 'CONCERT' | 'THEATER' | 'EXHIBITION' | 'DATE_MUSICAL' | 'DATE_THEATER' | 'DATE_CLASSIC' | 'DATE_EXHIBITION' | 'LIMITED_SALE' | 'WITH_KIDS' | 'DAEHAKRO' | 'REGION_SEOUL' | 'REGION_GYEONGGI' | 'REGION_BUSAN' | 'REGION_DAEGU' | 'REGION_DAEJEON' | 'REGION_NATIONWIDE', options?: RequestInit): Promise<removeHomeTagResponse> => {
  
  return orvalFetch<removeHomeTagResponse>(getRemoveHomeTagUrl(performanceId,tag),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


