/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorResponse,
  GetMyWishlistsParams,
  PagedWishlistResponse,
  Unit,
  WishlistStatusResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 특정 공연의 찜 여부를 확인합니다.
 * @summary 공연 찜 여부 확인
 */
export type checkWishlistStatusResponse200 = {
  data: WishlistStatusResponse
  status: 200
}
    
export type checkWishlistStatusResponseSuccess = (checkWishlistStatusResponse200) & {
  headers: Headers;
};
;

export type checkWishlistStatusResponse = (checkWishlistStatusResponseSuccess)

export const getCheckWishlistStatusUrl = (performanceId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/wishlists/${performanceId}`
}

export const checkWishlistStatus = async (performanceId: number, options?: RequestInit): Promise<checkWishlistStatusResponse> => {
  
  return orvalFetch<checkWishlistStatusResponse>(getCheckWishlistStatusUrl(performanceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 특정 공연을 찜 목록에 등록합니다.
 * @summary 찜 등록
 */
export type addWishlistResponse200 = {
  data: Unit
  status: 200
}

export type addWishlistResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type addWishlistResponseSuccess = (addWishlistResponse200) & {
  headers: Headers;
};
export type addWishlistResponseError = (addWishlistResponse404) & {
  headers: Headers;
};

export type addWishlistResponse = (addWishlistResponseSuccess | addWishlistResponseError)

export const getAddWishlistUrl = (performanceId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/wishlists/${performanceId}`
}

export const addWishlist = async (performanceId: number, options?: RequestInit): Promise<addWishlistResponse> => {
  
  return orvalFetch<addWishlistResponse>(getAddWishlistUrl(performanceId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * 특정 공연을 찜 목록에서 삭제합니다.
 * @summary 찜 해제
 */
export type removeWishlistResponse200 = {
  data: Unit
  status: 200
}
    
export type removeWishlistResponseSuccess = (removeWishlistResponse200) & {
  headers: Headers;
};
;

export type removeWishlistResponse = (removeWishlistResponseSuccess)

export const getRemoveWishlistUrl = (performanceId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/wishlists/${performanceId}`
}

export const removeWishlist = async (performanceId: number, options?: RequestInit): Promise<removeWishlistResponse> => {
  
  return orvalFetch<removeWishlistResponse>(getRemoveWishlistUrl(performanceId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * 로그인한 사용자의 찜 목록을 페이징 처리하여 조회합니다. (인피니티 스크롤 대응)
 * @summary 내 찜 목록 조회
 */
export type getMyWishlistsResponse200 = {
  data: PagedWishlistResponse
  status: 200
}
    
export type getMyWishlistsResponseSuccess = (getMyWishlistsResponse200) & {
  headers: Headers;
};
;

export type getMyWishlistsResponse = (getMyWishlistsResponseSuccess)

export const getGetMyWishlistsUrl = (params?: GetMyWishlistsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/wishlists/me?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/wishlists/me`
}

export const getMyWishlists = async (params?: GetMyWishlistsParams, options?: RequestInit): Promise<getMyWishlistsResponse> => {
  
  return orvalFetch<getMyWishlistsResponse>(getGetMyWishlistsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


