/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateReservationRequest,
  ErrorResponse,
  ReservationLookupRequest,
  ReservationResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 공연 예매를 생성합니다.
 * @summary 예매 생성
 */
export type createReservationResponse201 = {
  data: ReservationResponse
  status: 201
}

export type createReservationResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createReservationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type createReservationResponseSuccess = (createReservationResponse201) & {
  headers: Headers;
};
export type createReservationResponseError = (createReservationResponse400 | createReservationResponse404) & {
  headers: Headers;
};

export type createReservationResponse = (createReservationResponseSuccess | createReservationResponseError)

export const getCreateReservationUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/reservations`
}

export const createReservation = async (createReservationRequest: CreateReservationRequest, options?: RequestInit): Promise<createReservationResponse> => {
  
  return orvalFetch<createReservationResponse>(getCreateReservationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createReservationRequest,)
  }
);}


/**
 * 예매를 확정 처리합니다. (결제 완료)
 * @summary 예매 확정
 */
export type confirmReservationResponse200 = {
  data: ReservationResponse
  status: 200
}

export type confirmReservationResponse400 = {
  data: ErrorResponse
  status: 400
}

export type confirmReservationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type confirmReservationResponseSuccess = (confirmReservationResponse200) & {
  headers: Headers;
};
export type confirmReservationResponseError = (confirmReservationResponse400 | confirmReservationResponse404) & {
  headers: Headers;
};

export type confirmReservationResponse = (confirmReservationResponseSuccess | confirmReservationResponseError)

export const getConfirmReservationUrl = (id: number,) => {


  

  return `https://api.ticket.devhong.cc/api/reservations/${id}/confirm`
}

export const confirmReservation = async (id: number, options?: RequestInit): Promise<confirmReservationResponse> => {
  
  return orvalFetch<confirmReservationResponse>(getConfirmReservationUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * 예매를 취소합니다. 잔여석이 복구됩니다.
 * @summary 예매 취소
 */
export type cancelReservationResponse200 = {
  data: ReservationResponse
  status: 200
}

export type cancelReservationResponse400 = {
  data: ErrorResponse
  status: 400
}

export type cancelReservationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type cancelReservationResponseSuccess = (cancelReservationResponse200) & {
  headers: Headers;
};
export type cancelReservationResponseError = (cancelReservationResponse400 | cancelReservationResponse404) & {
  headers: Headers;
};

export type cancelReservationResponse = (cancelReservationResponseSuccess | cancelReservationResponseError)

export const getCancelReservationUrl = (id: number,) => {


  

  return `https://api.ticket.devhong.cc/api/reservations/${id}/cancel`
}

export const cancelReservation = async (id: number, options?: RequestInit): Promise<cancelReservationResponse> => {
  
  return orvalFetch<cancelReservationResponse>(getCancelReservationUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * 예매번호와 연락처로 예매를 조회합니다.
 * @summary 예매 조회 (비회원)
 */
export type lookupReservationResponse200 = {
  data: ReservationResponse
  status: 200
}

export type lookupReservationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type lookupReservationResponseSuccess = (lookupReservationResponse200) & {
  headers: Headers;
};
export type lookupReservationResponseError = (lookupReservationResponse404) & {
  headers: Headers;
};

export type lookupReservationResponse = (lookupReservationResponseSuccess | lookupReservationResponseError)

export const getLookupReservationUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/reservations/lookup`
}

export const lookupReservation = async (reservationLookupRequest: ReservationLookupRequest, options?: RequestInit): Promise<lookupReservationResponse> => {
  
  return orvalFetch<lookupReservationResponse>(getLookupReservationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reservationLookupRequest,)
  }
);}


/**
 * 예매 ID로 상세 정보를 조회합니다.
 * @summary 예매 상세 조회
 */
export type getReservationResponse200 = {
  data: ReservationResponse
  status: 200
}

export type getReservationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getReservationResponseSuccess = (getReservationResponse200) & {
  headers: Headers;
};
export type getReservationResponseError = (getReservationResponse404) & {
  headers: Headers;
};

export type getReservationResponse = (getReservationResponseSuccess | getReservationResponseError)

export const getGetReservationUrl = (id: number,) => {


  

  return `https://api.ticket.devhong.cc/api/reservations/${id}`
}

export const getReservation = async (id: number, options?: RequestInit): Promise<getReservationResponse> => {
  
  return orvalFetch<getReservationResponse>(getGetReservationUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 로그인한 사용자의 예매 목록을 조회합니다.
 * @summary 내 예매 목록 조회
 */
export type getMyReservationsResponse200 = {
  data: ReservationResponse[]
  status: 200
}

export type getMyReservationsResponse401 = {
  data: ErrorResponse
  status: 401
}
    
export type getMyReservationsResponseSuccess = (getMyReservationsResponse200) & {
  headers: Headers;
};
export type getMyReservationsResponseError = (getMyReservationsResponse401) & {
  headers: Headers;
};

export type getMyReservationsResponse = (getMyReservationsResponseSuccess | getMyReservationsResponseError)

export const getGetMyReservationsUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/reservations/my`
}

export const getMyReservations = async ( options?: RequestInit): Promise<getMyReservationsResponse> => {
  
  return orvalFetch<getMyReservationsResponse>(getGetMyReservationsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


