/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateSeatReservationRequest,
  ErrorResponse,
  GetMyHeldSeatsParams,
  GetScheduleSeatsParams,
  HoldSeatsRequest,
  HoldSeatsResponse,
  InitializeScheduleSeatsRequest,
  ReleaseSeatsRequest,
  ReleaseSeatsResponse,
  ReservationLookupRequest,
  ScheduleSeatMapResponse,
  ScheduleSeatResponse,
  SeatReservationResponse,
  SeatStatusSummary
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 점유한 좌석을 해제합니다.
 * @summary 좌석 점유 해제
 */
export type releaseSeatsResponse200 = {
  data: ReleaseSeatsResponse
  status: 200
}

export type releaseSeatsResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type releaseSeatsResponseSuccess = (releaseSeatsResponse200) & {
  headers: Headers;
};
export type releaseSeatsResponseError = (releaseSeatsResponse404) & {
  headers: Headers;
};

export type releaseSeatsResponse = (releaseSeatsResponseSuccess | releaseSeatsResponseError)

export const getReleaseSeatsUrl = (scheduleId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seats/release`
}

export const releaseSeats = async (scheduleId: number,
    releaseSeatsRequest: ReleaseSeatsRequest, options?: RequestInit): Promise<releaseSeatsResponse> => {
  
  return orvalFetch<releaseSeatsResponse>(getReleaseSeatsUrl(scheduleId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      releaseSeatsRequest,)
  }
);}


/**
 * 좌석을 임시 점유합니다. (최대 4석, 10분)
 * @summary 좌석 점유
 */
export type holdSeatsResponse200 = {
  data: HoldSeatsResponse
  status: 200
}

export type holdSeatsResponse400 = {
  data: ErrorResponse
  status: 400
}

export type holdSeatsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type holdSeatsResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type holdSeatsResponseSuccess = (holdSeatsResponse200) & {
  headers: Headers;
};
export type holdSeatsResponseError = (holdSeatsResponse400 | holdSeatsResponse404 | holdSeatsResponse409) & {
  headers: Headers;
};

export type holdSeatsResponse = (holdSeatsResponseSuccess | holdSeatsResponseError)

export const getHoldSeatsUrl = (scheduleId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seats/hold`
}

export const holdSeats = async (scheduleId: number,
    holdSeatsRequest: HoldSeatsRequest, options?: RequestInit): Promise<holdSeatsResponse> => {
  
  return orvalFetch<holdSeatsResponse>(getHoldSeatsUrl(scheduleId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      holdSeatsRequest,)
  }
);}


/**
 * 선택한 좌석으로 예매를 생성합니다.
 * @summary 좌석 선택 예매
 */
export type createSeatReservationResponse201 = {
  data: SeatReservationResponse
  status: 201
}

export type createSeatReservationResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createSeatReservationResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createSeatReservationResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type createSeatReservationResponseSuccess = (createSeatReservationResponse201) & {
  headers: Headers;
};
export type createSeatReservationResponseError = (createSeatReservationResponse400 | createSeatReservationResponse404 | createSeatReservationResponse409) & {
  headers: Headers;
};

export type createSeatReservationResponse = (createSeatReservationResponseSuccess | createSeatReservationResponseError)

export const getCreateSeatReservationUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/reservations/seats`
}

export const createSeatReservation = async (createSeatReservationRequest: CreateSeatReservationRequest, options?: RequestInit): Promise<createSeatReservationResponse> => {
  
  return orvalFetch<createSeatReservationResponse>(getCreateSeatReservationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSeatReservationRequest,)
  }
);}


/**
 * 좌석 예매를 확정 처리합니다.
 * @summary 좌석 예매 확정
 */
export type confirmSeatReservationResponse200 = {
  data: SeatReservationResponse
  status: 200
}

export type confirmSeatReservationResponse400 = {
  data: ErrorResponse
  status: 400
}

export type confirmSeatReservationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type confirmSeatReservationResponseSuccess = (confirmSeatReservationResponse200) & {
  headers: Headers;
};
export type confirmSeatReservationResponseError = (confirmSeatReservationResponse400 | confirmSeatReservationResponse404) & {
  headers: Headers;
};

export type confirmSeatReservationResponse = (confirmSeatReservationResponseSuccess | confirmSeatReservationResponseError)

export const getConfirmSeatReservationUrl = (id: number,) => {


  

  return `https://api.ticket.devhong.cc/api/reservations/seats/${id}/confirm`
}

export const confirmSeatReservation = async (id: number, options?: RequestInit): Promise<confirmSeatReservationResponse> => {
  
  return orvalFetch<confirmSeatReservationResponse>(getConfirmSeatReservationUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * 좌석 예매를 취소합니다. 좌석이 다시 AVAILABLE 상태가 됩니다.
 * @summary 좌석 예매 취소
 */
export type cancelSeatReservationResponse200 = {
  data: SeatReservationResponse
  status: 200
}

export type cancelSeatReservationResponse400 = {
  data: ErrorResponse
  status: 400
}

export type cancelSeatReservationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type cancelSeatReservationResponseSuccess = (cancelSeatReservationResponse200) & {
  headers: Headers;
};
export type cancelSeatReservationResponseError = (cancelSeatReservationResponse400 | cancelSeatReservationResponse404) & {
  headers: Headers;
};

export type cancelSeatReservationResponse = (cancelSeatReservationResponseSuccess | cancelSeatReservationResponseError)

export const getCancelSeatReservationUrl = (id: number,) => {


  

  return `https://api.ticket.devhong.cc/api/reservations/seats/${id}/cancel`
}

export const cancelSeatReservation = async (id: number, options?: RequestInit): Promise<cancelSeatReservationResponse> => {
  
  return orvalFetch<cancelSeatReservationResponse>(getCancelSeatReservationUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * 예매번호와 연락처로 좌석 예매를 조회합니다.
 * @summary 좌석 예매 조회 (비회원)
 */
export type lookupSeatReservationResponse200 = {
  data: SeatReservationResponse
  status: 200
}

export type lookupSeatReservationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type lookupSeatReservationResponseSuccess = (lookupSeatReservationResponse200) & {
  headers: Headers;
};
export type lookupSeatReservationResponseError = (lookupSeatReservationResponse404) & {
  headers: Headers;
};

export type lookupSeatReservationResponse = (lookupSeatReservationResponseSuccess | lookupSeatReservationResponseError)

export const getLookupSeatReservationUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/reservations/seats/lookup`
}

export const lookupSeatReservation = async (reservationLookupRequest: ReservationLookupRequest, options?: RequestInit): Promise<lookupSeatReservationResponse> => {
  
  return orvalFetch<lookupSeatReservationResponse>(getLookupSeatReservationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reservationLookupRequest,)
  }
);}


/**
 * 공연 회차에 좌석을 초기화합니다.

**권한: ADMIN**
 * @summary 회차별 좌석 초기화
 */
export type initializeScheduleSeatsResponse201 = {
  data: ScheduleSeatMapResponse
  status: 201
}

export type initializeScheduleSeatsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type initializeScheduleSeatsResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type initializeScheduleSeatsResponseSuccess = (initializeScheduleSeatsResponse201) & {
  headers: Headers;
};
export type initializeScheduleSeatsResponseError = (initializeScheduleSeatsResponse404 | initializeScheduleSeatsResponse409) & {
  headers: Headers;
};

export type initializeScheduleSeatsResponse = (initializeScheduleSeatsResponseSuccess | initializeScheduleSeatsResponseError)

export const getInitializeScheduleSeatsUrl = (scheduleId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/admin/schedules/${scheduleId}/seats/initialize`
}

export const initializeScheduleSeats = async (scheduleId: number,
    initializeScheduleSeatsRequest: InitializeScheduleSeatsRequest, options?: RequestInit): Promise<initializeScheduleSeatsResponse> => {
  
  return orvalFetch<initializeScheduleSeatsResponse>(getInitializeScheduleSeatsUrl(scheduleId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      initializeScheduleSeatsRequest,)
  }
);}


/**
 * 공연 회차의 모든 좌석 상태를 조회합니다. (좌석배치도 렌더링용)
 * @summary 회차별 좌석 상태 조회
 */
export type getScheduleSeatsResponse200 = {
  data: ScheduleSeatMapResponse
  status: 200
}

export type getScheduleSeatsResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getScheduleSeatsResponseSuccess = (getScheduleSeatsResponse200) & {
  headers: Headers;
};
export type getScheduleSeatsResponseError = (getScheduleSeatsResponse404) & {
  headers: Headers;
};

export type getScheduleSeatsResponse = (getScheduleSeatsResponseSuccess | getScheduleSeatsResponseError)

export const getGetScheduleSeatsUrl = (scheduleId: number,
    params?: GetScheduleSeatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seats?${stringifiedParams}` : `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seats`
}

export const getScheduleSeats = async (scheduleId: number,
    params?: GetScheduleSeatsParams, options?: RequestInit): Promise<getScheduleSeatsResponse> => {
  
  return orvalFetch<getScheduleSeatsResponse>(getGetScheduleSeatsUrl(scheduleId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 공연 회차의 좌석 상태별 수량을 조회합니다.
 * @summary 회차별 좌석 상태 요약
 */
export type getSeatStatusSummaryResponse200 = {
  data: SeatStatusSummary
  status: 200
}

export type getSeatStatusSummaryResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getSeatStatusSummaryResponseSuccess = (getSeatStatusSummaryResponse200) & {
  headers: Headers;
};
export type getSeatStatusSummaryResponseError = (getSeatStatusSummaryResponse404) & {
  headers: Headers;
};

export type getSeatStatusSummaryResponse = (getSeatStatusSummaryResponseSuccess | getSeatStatusSummaryResponseError)

export const getGetSeatStatusSummaryUrl = (scheduleId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seats/summary`
}

export const getSeatStatusSummary = async (scheduleId: number, options?: RequestInit): Promise<getSeatStatusSummaryResponse> => {
  
  return orvalFetch<getSeatStatusSummaryResponse>(getGetSeatStatusSummaryUrl(scheduleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 현재 점유 중인 좌석 목록을 조회합니다.
 * @summary 내 점유 좌석 조회
 */
export type getMyHeldSeatsResponse200 = {
  data: ScheduleSeatResponse[]
  status: 200
}
    
export type getMyHeldSeatsResponseSuccess = (getMyHeldSeatsResponse200) & {
  headers: Headers;
};
;

export type getMyHeldSeatsResponse = (getMyHeldSeatsResponseSuccess)

export const getGetMyHeldSeatsUrl = (scheduleId: number,
    params?: GetMyHeldSeatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seats/my-holds?${stringifiedParams}` : `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seats/my-holds`
}

export const getMyHeldSeats = async (scheduleId: number,
    params?: GetMyHeldSeatsParams, options?: RequestInit): Promise<getMyHeldSeatsResponse> => {
  
  return orvalFetch<getMyHeldSeatsResponse>(getGetMyHeldSeatsUrl(scheduleId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 좌석 예매 상세 정보를 조회합니다.
 * @summary 좌석 예매 상세 조회
 */
export type getSeatReservationResponse200 = {
  data: SeatReservationResponse
  status: 200
}

export type getSeatReservationResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getSeatReservationResponseSuccess = (getSeatReservationResponse200) & {
  headers: Headers;
};
export type getSeatReservationResponseError = (getSeatReservationResponse404) & {
  headers: Headers;
};

export type getSeatReservationResponse = (getSeatReservationResponseSuccess | getSeatReservationResponseError)

export const getGetSeatReservationUrl = (id: number,) => {


  

  return `https://api.ticket.devhong.cc/api/reservations/seats/${id}`
}

export const getSeatReservation = async (id: number, options?: RequestInit): Promise<getSeatReservationResponse> => {
  
  return orvalFetch<getSeatReservationResponse>(getGetSeatReservationUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 로그인한 사용자의 좌석 예매 목록을 조회합니다.
 * @summary 내 좌석 예매 목록 조회
 */
export type getMySeatReservationsResponse200 = {
  data: SeatReservationResponse[]
  status: 200
}

export type getMySeatReservationsResponse401 = {
  data: ErrorResponse
  status: 401
}
    
export type getMySeatReservationsResponseSuccess = (getMySeatReservationsResponse200) & {
  headers: Headers;
};
export type getMySeatReservationsResponseError = (getMySeatReservationsResponse401) & {
  headers: Headers;
};

export type getMySeatReservationsResponse = (getMySeatReservationsResponseSuccess | getMySeatReservationsResponseError)

export const getGetMySeatReservationsUrl = () => {


  

  return `https://api.ticket.devhong.cc/api/reservations/seats/my`
}

export const getMySeatReservations = async ( options?: RequestInit): Promise<getMySeatReservationsResponse> => {
  
  return orvalFetch<getMySeatReservationsResponse>(getGetMySeatReservationsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


