/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type {
  AvailableScheduleResponse,
  CreatePerformanceRequest,
  ErrorResponse,
  GetAvailableSchedulesByDateParams,
  PerformanceResponse,
  Unit,
  UpdatePerformanceRequest
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * ID로 특정 공연의 정보를 조회합니다.

**권한: 누구나**
 * @summary 단일 공연 조회
 */
export type getPerformanceResponse200 = {
  data: PerformanceResponse
  status: 200
}

export type getPerformanceResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getPerformanceResponseSuccess = (getPerformanceResponse200) & {
  headers: Headers;
};
export type getPerformanceResponseError = (getPerformanceResponse404) & {
  headers: Headers;
};

export type getPerformanceResponse = (getPerformanceResponseSuccess | getPerformanceResponseError)

export const getGetPerformanceUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/performances/${id}`
}

export const getPerformance = async (id: number, options?: RequestInit): Promise<getPerformanceResponse> => {
  
  return orvalFetch<getPerformanceResponse>(getGetPerformanceUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 특정 공연의 정보를 수정합니다.

**권한: ADMIN**
 * @summary 공연 정보 수정
 */
export type updatePerformanceResponse200 = {
  data: PerformanceResponse
  status: 200
}

export type updatePerformanceResponse400 = {
  data: ErrorResponse
  status: 400
}

export type updatePerformanceResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updatePerformanceResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type updatePerformanceResponseSuccess = (updatePerformanceResponse200) & {
  headers: Headers;
};
export type updatePerformanceResponseError = (updatePerformanceResponse400 | updatePerformanceResponse403 | updatePerformanceResponse404) & {
  headers: Headers;
};

export type updatePerformanceResponse = (updatePerformanceResponseSuccess | updatePerformanceResponseError)

export const getUpdatePerformanceUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/performances/${id}`
}

export const updatePerformance = async (id: number,
    updatePerformanceRequest: UpdatePerformanceRequest, options?: RequestInit): Promise<updatePerformanceResponse> => {
  
  return orvalFetch<updatePerformanceResponse>(getUpdatePerformanceUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePerformanceRequest,)
  }
);}


/**
 * 특정 공연을 삭제합니다.

**권한: ADMIN**
 * @summary 공연 삭제
 */
export type deletePerformanceResponse204 = {
  data: Unit
  status: 204
}

export type deletePerformanceResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deletePerformanceResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type deletePerformanceResponseSuccess = (deletePerformanceResponse204) & {
  headers: Headers;
};
export type deletePerformanceResponseError = (deletePerformanceResponse403 | deletePerformanceResponse404) & {
  headers: Headers;
};

export type deletePerformanceResponse = (deletePerformanceResponseSuccess | deletePerformanceResponseError)

export const getDeletePerformanceUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/performances/${id}`
}

export const deletePerformance = async (id: number, options?: RequestInit): Promise<deletePerformanceResponse> => {
  
  return orvalFetch<deletePerformanceResponse>(getDeletePerformanceUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * 모든 공연 목록을 조회합니다.

**권한: 누구나**
 * @summary 모든 공연 조회
 */
export type getAllPerformancesResponse200 = {
  data: PerformanceResponse[]
  status: 200
}
    
export type getAllPerformancesResponseSuccess = (getAllPerformancesResponse200) & {
  headers: Headers;
};
;

export type getAllPerformancesResponse = (getAllPerformancesResponseSuccess)

export const getGetAllPerformancesUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/performances`
}

export const getAllPerformances = async ( options?: RequestInit): Promise<getAllPerformancesResponse> => {
  
  return orvalFetch<getAllPerformancesResponse>(getGetAllPerformancesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 새로운 공연 정보를 생성합니다.

**권한: ADMIN**
 * @summary 공연 생성
 */
export type createPerformanceResponse201 = {
  data: PerformanceResponse
  status: 201
}

export type createPerformanceResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createPerformanceResponse403 = {
  data: ErrorResponse
  status: 403
}
    
export type createPerformanceResponseSuccess = (createPerformanceResponse201) & {
  headers: Headers;
};
export type createPerformanceResponseError = (createPerformanceResponse400 | createPerformanceResponse403) & {
  headers: Headers;
};

export type createPerformanceResponse = (createPerformanceResponseSuccess | createPerformanceResponseError)

export const getCreatePerformanceUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/performances`
}

export const createPerformance = async (createPerformanceRequest: CreatePerformanceRequest, options?: RequestInit): Promise<createPerformanceResponse> => {
  
  return orvalFetch<createPerformanceResponse>(getCreatePerformanceUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPerformanceRequest,)
  }
);}


/**
 * 해당 공연의 특정 날짜에 예매 가능한 회차 목록을 조회합니다.

- 공연시간 내림차순 정렬
- 각 좌석 등급의 잔여석 수 포함

**권한: 누구나**
 * @summary 특정 날짜의 예매 가능 회차 목록 조회
 */
export type getAvailableSchedulesByDateResponse200 = {
  data: AvailableScheduleResponse[]
  status: 200
}

export type getAvailableSchedulesByDateResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getAvailableSchedulesByDateResponseSuccess = (getAvailableSchedulesByDateResponse200) & {
  headers: Headers;
};
export type getAvailableSchedulesByDateResponseError = (getAvailableSchedulesByDateResponse404) & {
  headers: Headers;
};

export type getAvailableSchedulesByDateResponse = (getAvailableSchedulesByDateResponseSuccess | getAvailableSchedulesByDateResponseError)

export const getGetAvailableSchedulesByDateUrl = (id: number,
    params: GetAvailableSchedulesByDateParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/performances/${id}/schedules?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/performances/${id}/schedules`
}

export const getAvailableSchedulesByDate = async (id: number,
    params: GetAvailableSchedulesByDateParams, options?: RequestInit): Promise<getAvailableSchedulesByDateResponse> => {
  
  return orvalFetch<getAvailableSchedulesByDateResponse>(getGetAvailableSchedulesByDateUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 해당 공연의 예매 가능한 회차 날짜 목록을 조회합니다.

- 티켓 판매가 시작되고 공연이 아직 시작하지 않은 회차만 반환

**권한: 누구나**
 * @summary 예매 가능 회차 날짜 목록 조회
 */
export type getAvailableScheduleDatesResponse200 = {
  data: string[]
  status: 200
}

export type getAvailableScheduleDatesResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getAvailableScheduleDatesResponseSuccess = (getAvailableScheduleDatesResponse200) & {
  headers: Headers;
};
export type getAvailableScheduleDatesResponseError = (getAvailableScheduleDatesResponse404) & {
  headers: Headers;
};

export type getAvailableScheduleDatesResponse = (getAvailableScheduleDatesResponseSuccess | getAvailableScheduleDatesResponseError)

export const getGetAvailableScheduleDatesUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/performances/${id}/schedules/dates`
}

export const getAvailableScheduleDates = async (id: number, options?: RequestInit): Promise<getAvailableScheduleDatesResponse> => {
  
  return orvalFetch<getAvailableScheduleDatesResponse>(getGetAvailableScheduleDatesUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


