/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreatePerformanceScheduleRequest,
  PerformanceScheduleResponse,
  Unit,
  UpdatePerformanceScheduleRequest
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * ID로 특정 공연 회차의 정보를 조회합니다.

**권한: ADMIN**
 * @summary 단일 공연 회차 조회
 */
export type getSchedule1Response200 = {
  data: PerformanceScheduleResponse
  status: 200
}
    
export type getSchedule1ResponseSuccess = (getSchedule1Response200) & {
  headers: Headers;
};
;

export type getSchedule1Response = (getSchedule1ResponseSuccess)

export const getGetSchedule1Url = (scheduleId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/performances/schedules/${scheduleId}`
}

export const getSchedule1 = async (scheduleId: number, options?: RequestInit): Promise<getSchedule1Response> => {
  
  return orvalFetch<getSchedule1Response>(getGetSchedule1Url(scheduleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 특정 공연 회차의 정보를 수정합니다.

**권한: ADMIN**

**[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
 * @summary 공연 회차 수정
 */
export type updateScheduleResponse200 = {
  data: PerformanceScheduleResponse
  status: 200
}
    
export type updateScheduleResponseSuccess = (updateScheduleResponse200) & {
  headers: Headers;
};
;

export type updateScheduleResponse = (updateScheduleResponseSuccess)

export const getUpdateScheduleUrl = (scheduleId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/performances/schedules/${scheduleId}`
}

export const updateSchedule = async (scheduleId: number,
    updatePerformanceScheduleRequest: UpdatePerformanceScheduleRequest, options?: RequestInit): Promise<updateScheduleResponse> => {
  
  return orvalFetch<updateScheduleResponse>(getUpdateScheduleUrl(scheduleId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePerformanceScheduleRequest,)
  }
);}


/**
 * 특정 공연 회차를 삭제합니다.

**권한: ADMIN**

**[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
 * @summary 공연 회차 삭제
 */
export type deleteScheduleResponse200 = {
  data: Unit
  status: 200
}
    
export type deleteScheduleResponseSuccess = (deleteScheduleResponse200) & {
  headers: Headers;
};
;

export type deleteScheduleResponse = (deleteScheduleResponseSuccess)

export const getDeleteScheduleUrl = (scheduleId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/performances/schedules/${scheduleId}`
}

export const deleteSchedule = async (scheduleId: number, options?: RequestInit): Promise<deleteScheduleResponse> => {
  
  return orvalFetch<deleteScheduleResponse>(getDeleteScheduleUrl(scheduleId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * 특정 공연에 대한 모든 회차 목록을 조회합니다.

**권한: ADMIN**
 * @summary 특정 공연의 모든 회차 조회
 */
export type getAllSchedulesResponse200 = {
  data: PerformanceScheduleResponse[]
  status: 200
}
    
export type getAllSchedulesResponseSuccess = (getAllSchedulesResponse200) & {
  headers: Headers;
};
;

export type getAllSchedulesResponse = (getAllSchedulesResponseSuccess)

export const getGetAllSchedulesUrl = (performanceId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/performances/${performanceId}/schedules`
}

export const getAllSchedules = async (performanceId: number, options?: RequestInit): Promise<getAllSchedulesResponse> => {
  
  return orvalFetch<getAllSchedulesResponse>(getGetAllSchedulesUrl(performanceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 특정 공연에 대한 새로운 회차와 티켓 가격 옵션을 생성합니다.

**권한: ADMIN**

**[Audit Log]** 이 작업은 감사 로그에 기록됩니다.
 * @summary 공연 회차 생성
 */
export type createScheduleResponse200 = {
  data: PerformanceScheduleResponse
  status: 200
}
    
export type createScheduleResponseSuccess = (createScheduleResponse200) & {
  headers: Headers;
};
;

export type createScheduleResponse = (createScheduleResponseSuccess)

export const getCreateScheduleUrl = (performanceId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/performances/${performanceId}/schedules`
}

export const createSchedule = async (performanceId: number,
    createPerformanceScheduleRequest: CreatePerformanceScheduleRequest, options?: RequestInit): Promise<createScheduleResponse> => {
  
  return orvalFetch<createScheduleResponse>(getCreateScheduleUrl(performanceId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPerformanceScheduleRequest,)
  }
);}


