/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  CouponCreateRequest,
  CouponResponse,
  CouponUpdateRequest,
  ErrorResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 특정 쿠폰의 상세 정보를 조회합니다.

**권한: ADMIN**
 * @summary 쿠폰 상세 조회
 */
export type getCouponResponse200 = {
  data: CouponResponse
  status: 200
}

export type getCouponResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getCouponResponseSuccess = (getCouponResponse200) & {
  headers: Headers;
};
export type getCouponResponseError = (getCouponResponse404) & {
  headers: Headers;
};

export type getCouponResponse = (getCouponResponseSuccess | getCouponResponseError)

export const getGetCouponUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/coupons/${id}`
}

export const getCoupon = async (id: number, options?: RequestInit): Promise<getCouponResponse> => {
  
  return orvalFetch<getCouponResponse>(getGetCouponUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 쿠폰 정보를 수정합니다.

**권한: ADMIN**
 * @summary 쿠폰 수정
 */
export type updateCouponResponse200 = {
  data: CouponResponse
  status: 200
}

export type updateCouponResponse400 = {
  data: ErrorResponse
  status: 400
}

export type updateCouponResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type updateCouponResponseSuccess = (updateCouponResponse200) & {
  headers: Headers;
};
export type updateCouponResponseError = (updateCouponResponse400 | updateCouponResponse404) & {
  headers: Headers;
};

export type updateCouponResponse = (updateCouponResponseSuccess | updateCouponResponseError)

export const getUpdateCouponUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/coupons/${id}`
}

export const updateCoupon = async (id: number,
    couponUpdateRequest: CouponUpdateRequest, options?: RequestInit): Promise<updateCouponResponse> => {
  
  return orvalFetch<updateCouponResponse>(getUpdateCouponUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      couponUpdateRequest,)
  }
);}


/**
 * 전체 쿠폰 목록을 조회합니다.

**권한: ADMIN**
 * @summary 쿠폰 목록 조회
 */
export type getAllCouponsResponse200 = {
  data: CouponResponse[]
  status: 200
}
    
export type getAllCouponsResponseSuccess = (getAllCouponsResponse200) & {
  headers: Headers;
};
;

export type getAllCouponsResponse = (getAllCouponsResponseSuccess)

export const getGetAllCouponsUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/admin/coupons`
}

export const getAllCoupons = async ( options?: RequestInit): Promise<getAllCouponsResponse> => {
  
  return orvalFetch<getAllCouponsResponse>(getGetAllCouponsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 새로운 쿠폰을 생성합니다.

**권한: ADMIN**
 * @summary 쿠폰 생성
 */
export type createCouponResponse200 = {
  data: CouponResponse
  status: 200
}

export type createCouponResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type createCouponResponseSuccess = (createCouponResponse200) & {
  headers: Headers;
};
export type createCouponResponseError = (createCouponResponse400) & {
  headers: Headers;
};

export type createCouponResponse = (createCouponResponseSuccess | createCouponResponseError)

export const getCreateCouponUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/admin/coupons`
}

export const createCoupon = async (couponCreateRequest: CouponCreateRequest, options?: RequestInit): Promise<createCouponResponse> => {
  
  return orvalFetch<createCouponResponse>(getCreateCouponUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      couponCreateRequest,)
  }
);}


/**
 * 쿠폰을 비활성화합니다. 비활성화된 쿠폰은 사용이 불가합니다.

**권한: ADMIN**
 * @summary 쿠폰 비활성화
 */
export type deactivateCouponResponse200 = {
  data: CouponResponse
  status: 200
}

export type deactivateCouponResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type deactivateCouponResponseSuccess = (deactivateCouponResponse200) & {
  headers: Headers;
};
export type deactivateCouponResponseError = (deactivateCouponResponse404) & {
  headers: Headers;
};

export type deactivateCouponResponse = (deactivateCouponResponseSuccess | deactivateCouponResponseError)

export const getDeactivateCouponUrl = (id: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/coupons/${id}/deactivate`
}

export const deactivateCoupon = async (id: number, options?: RequestInit): Promise<deactivateCouponResponse> => {
  
  return orvalFetch<deactivateCouponResponse>(getDeactivateCouponUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}


