/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type {
  AdminLoginRequest,
  AdminResponse,
  AdminSignupRequest,
  ErrorResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 새로운 관리자를 생성합니다.

**권한: 누구나**
 * @summary 관리자 회원가입
 */
export type signup1Response201 = {
  data: AdminResponse
  status: 201
}

export type signup1Response400 = {
  data: ErrorResponse
  status: 400
}

export type signup1Response409 = {
  data: ErrorResponse
  status: 409
}
    
export type signup1ResponseSuccess = (signup1Response201) & {
  headers: Headers;
};
export type signup1ResponseError = (signup1Response400 | signup1Response409) & {
  headers: Headers;
};

export type signup1Response = (signup1ResponseSuccess | signup1ResponseError)

export const getSignup1Url = () => {


  

  return `https://api.ticket.devhong.cc/api/admin/auth/signup`
}

export const signup1 = async (adminSignupRequest: AdminSignupRequest, options?: RequestInit): Promise<signup1Response> => {
  
  return orvalFetch<signup1Response>(getSignup1Url(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminSignupRequest,)
  }
);}


/**
 * 관리자 세션을 종료하고 인증 쿠키를 삭제합니다.

**권한: 누구나**
 * @summary 관리자 로그아웃
 */
export type logout1Response200 = {
  data: void
  status: 200
}
    
export type logout1ResponseSuccess = (logout1Response200) & {
  headers: Headers;
};
;

export type logout1Response = (logout1ResponseSuccess)

export const getLogout1Url = () => {


  

  return `https://api.ticket.devhong.cc/api/admin/auth/logout`
}

export const logout1 = async ( options?: RequestInit): Promise<logout1Response> => {
  
  return orvalFetch<logout1Response>(getLogout1Url(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * 로그인 ID와 비밀번호로 로그인하고 JWT 토큰을 발급받습니다.

**권한: 누구나**
 * @summary 관리자 로그인
 */
export type login1Response200 = {
  data: void
  status: 200
}

export type login1Response401 = {
  data: ErrorResponse
  status: 401
}
    
export type login1ResponseSuccess = (login1Response200) & {
  headers: Headers;
};
export type login1ResponseError = (login1Response401) & {
  headers: Headers;
};

export type login1Response = (login1ResponseSuccess | login1ResponseError)

export const getLogin1Url = () => {


  

  return `https://api.ticket.devhong.cc/api/admin/auth/login`
}

export const login1 = async (adminLoginRequest: AdminLoginRequest, options?: RequestInit): Promise<login1Response> => {
  
  return orvalFetch<login1Response>(getLogin1Url(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminLoginRequest,)
  }
);}


