/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorResponse,
  ScheduleSeatStatusResponse,
  SeatHoldRequest,
  SeatHoldResponse,
  SeatStatusResponse,
  Unit
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 점유 중인 좌석을 예약 확정합니다. (결제 완료 후 호출)

**권한: USER, ADMIN**
 * @summary 좌석 예약 확정
 */
export type reserveSeatsResponse200 = {
  data: SeatStatusResponse[]
  status: 200
}

export type reserveSeatsResponse400 = {
  data: ErrorResponse
  status: 400
}

export type reserveSeatsResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type reserveSeatsResponseSuccess = (reserveSeatsResponse200) & {
  headers: Headers;
};
export type reserveSeatsResponseError = (reserveSeatsResponse400 | reserveSeatsResponse404) & {
  headers: Headers;
};

export type reserveSeatsResponse = (reserveSeatsResponseSuccess | reserveSeatsResponseError)

export const getReserveSeatsUrl = (scheduleId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seats/reserve`
}

export const reserveSeats = async (scheduleId: number, options?: RequestInit): Promise<reserveSeatsResponse> => {
  
  return orvalFetch<reserveSeatsResponse>(getReserveSeatsUrl(scheduleId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * 좌석을 점유합니다. 점유 시간은 10분이며, 최대 4석까지 선택 가능합니다.

**권한: USER, ADMIN**
 * @summary 좌석 점유
 */
export type holdSeatsResponse200 = {
  data: SeatHoldResponse
  status: 200
}

export type holdSeatsResponse400 = {
  data: ErrorResponse
  status: 400
}

export type holdSeatsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type holdSeatsResponse409 = {
  data: ErrorResponse
  status: 409
}
    
export type holdSeatsResponseSuccess = (holdSeatsResponse200) & {
  headers: Headers;
};
export type holdSeatsResponseError = (holdSeatsResponse400 | holdSeatsResponse404 | holdSeatsResponse409) & {
  headers: Headers;
};

export type holdSeatsResponse = (holdSeatsResponseSuccess | holdSeatsResponseError)

export const getHoldSeatsUrl = (scheduleId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seats/hold`
}

export const holdSeats = async (scheduleId: number,
    seatHoldRequest: SeatHoldRequest, options?: RequestInit): Promise<holdSeatsResponse> => {
  
  return orvalFetch<holdSeatsResponse>(getHoldSeatsUrl(scheduleId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      seatHoldRequest,)
  }
);}


/**
 * 점유 중인 좌석을 해제합니다.

**권한: USER, ADMIN**
 * @summary 좌석 점유 해제
 */
export type releaseSeatsResponse204 = {
  data: Unit
  status: 204
}

export type releaseSeatsResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type releaseSeatsResponseSuccess = (releaseSeatsResponse204) & {
  headers: Headers;
};
export type releaseSeatsResponseError = (releaseSeatsResponse404) & {
  headers: Headers;
};

export type releaseSeatsResponse = (releaseSeatsResponseSuccess | releaseSeatsResponseError)

export const getReleaseSeatsUrl = (scheduleId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seats/hold`
}

export const releaseSeats = async (scheduleId: number, options?: RequestInit): Promise<releaseSeatsResponse> => {
  
  return orvalFetch<releaseSeatsResponse>(getReleaseSeatsUrl(scheduleId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * 특정 회차의 좌석 상태 목록을 조회합니다. PENDING(점유 중), RESERVED(예약 완료) 상태인 좌석만 반환합니다.

**권한: 인증 불필요**
 * @summary 회차별 좌석 상태 조회
 */
export type getSeatStatusResponse200 = {
  data: ScheduleSeatStatusResponse
  status: 200
}

export type getSeatStatusResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getSeatStatusResponseSuccess = (getSeatStatusResponse200) & {
  headers: Headers;
};
export type getSeatStatusResponseError = (getSeatStatusResponse404) & {
  headers: Headers;
};

export type getSeatStatusResponse = (getSeatStatusResponseSuccess | getSeatStatusResponseError)

export const getGetSeatStatusUrl = (scheduleId: number,) => {


  

  return `https://api.ticket.devhong.cc/api/schedules/${scheduleId}/seat-status`
}

export const getSeatStatus = async (scheduleId: number, options?: RequestInit): Promise<getSeatStatusResponse> => {
  
  return orvalFetch<getSeatStatusResponse>(getGetSeatStatusUrl(scheduleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


