/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  HomeSectionResponse,
  HomeSectionsResponse,
  HomeTagWithPerformancesResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 홈 화면의 특정 태그에 등록된 공연 목록을 조회합니다.
 * @summary 특정 태그의 공연 목록 조회
 */
export type getPerformancesByTagResponse200 = {
  data: HomeTagWithPerformancesResponse
  status: 200
}
    
export type getPerformancesByTagResponseSuccess = (getPerformancesByTagResponse200) & {
  headers: Headers;
};
;

export type getPerformancesByTagResponse = (getPerformancesByTagResponseSuccess)

export const getGetPerformancesByTagUrl = (tag: 'WEEKLY_OPEN' | 'MUSICAL' | 'CONCERT' | 'THEATER' | 'EXHIBITION' | 'DATE_MUSICAL' | 'DATE_THEATER' | 'DATE_CLASSIC' | 'DATE_EXHIBITION' | 'LIMITED_SALE' | 'WITH_KIDS' | 'DAEHAKRO' | 'REGION_SEOUL' | 'REGION_GYEONGGI' | 'REGION_BUSAN' | 'REGION_DAEGU' | 'REGION_DAEJEON' | 'REGION_NATIONWIDE',) => {


  

  return `https://ticket-api.devhong.cc/api/home/tags/${tag}/performances`
}

export const getPerformancesByTag = async (tag: 'WEEKLY_OPEN' | 'MUSICAL' | 'CONCERT' | 'THEATER' | 'EXHIBITION' | 'DATE_MUSICAL' | 'DATE_THEATER' | 'DATE_CLASSIC' | 'DATE_EXHIBITION' | 'LIMITED_SALE' | 'WITH_KIDS' | 'DAEHAKRO' | 'REGION_SEOUL' | 'REGION_GYEONGGI' | 'REGION_BUSAN' | 'REGION_DAEGU' | 'REGION_DAEJEON' | 'REGION_NATIONWIDE', options?: RequestInit): Promise<getPerformancesByTagResponse> => {
  
  return orvalFetch<getPerformancesByTagResponse>(getGetPerformancesByTagUrl(tag),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 
홈 화면에 표시할 전체 섹션과 공연 목록을 조회합니다.

**섹션 구조:**
1. 인기티켓 (금주오픈티켓, 뮤지컬, 콘서트, 연극, 전시/행사)
2. 데이트코스 (뮤지컬, 연극, 클래식, 전시)
3. 이런 티켓은 어때요? (한정특가, 아이와 함께, 대학로공연)
4. 어디로 떠나볼까요? (서울, 경기, 부산, 대구, 대전, 전국)

**참고:**
- visible=true인 공연만 노출됩니다.
- 각 태그 내 공연은 관리자가 지정한 순서대로 정렬됩니다.
        
 * @summary 홈 전체 섹션 조회
 */
export type getAllSectionsResponse200 = {
  data: HomeSectionsResponse
  status: 200
}
    
export type getAllSectionsResponseSuccess = (getAllSectionsResponse200) & {
  headers: Headers;
};
;

export type getAllSectionsResponse = (getAllSectionsResponseSuccess)

export const getGetAllSectionsUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/home/sections`
}

export const getAllSections = async ( options?: RequestInit): Promise<getAllSectionsResponse> => {
  
  return orvalFetch<getAllSectionsResponse>(getGetAllSectionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 홈 화면의 특정 섹션과 해당 섹션의 태그별 공연 목록을 조회합니다.
 * @summary 특정 섹션 조회
 */
export type getSectionResponse200 = {
  data: HomeSectionResponse
  status: 200
}
    
export type getSectionResponseSuccess = (getSectionResponse200) & {
  headers: Headers;
};
;

export type getSectionResponse = (getSectionResponseSuccess)

export const getGetSectionUrl = (section: 'POPULAR_TICKET' | 'DATE_COURSE' | 'RECOMMENDED' | 'REGION',) => {


  

  return `https://ticket-api.devhong.cc/api/home/sections/${section}`
}

export const getSection = async (section: 'POPULAR_TICKET' | 'DATE_COURSE' | 'RECOMMENDED' | 'REGION', options?: RequestInit): Promise<getSectionResponse> => {
  
  return orvalFetch<getSectionResponse>(getGetSectionUrl(section),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


