/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  AvailableCouponResponse,
  CouponValidateRequest,
  CouponValidateResponse,
  ErrorResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 좌석별로 적용된 쿠폰의 유효성을 검증하고 할인 금액을 계산합니다.

**권한: USER**
 * @summary 좌석별 쿠폰 적용 검증
 */
export type validateCouponsResponse200 = {
  data: CouponValidateResponse
  status: 200
}

export type validateCouponsResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type validateCouponsResponseSuccess = (validateCouponsResponse200) & {
  headers: Headers;
};
export type validateCouponsResponseError = (validateCouponsResponse400) & {
  headers: Headers;
};

export type validateCouponsResponse = (validateCouponsResponseSuccess | validateCouponsResponseError)

export const getValidateCouponsUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/coupons/validate`
}

export const validateCoupons = async (couponValidateRequest: CouponValidateRequest, options?: RequestInit): Promise<validateCouponsResponse> => {
  
  return orvalFetch<validateCouponsResponse>(getValidateCouponsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      couponValidateRequest,)
  }
);}


/**
 * 현재 사용 가능한 쿠폰 목록을 조회합니다. 남은 사용 횟수가 0인 쿠폰은 제외됩니다.

**권한: USER**
 * @summary 사용 가능한 쿠폰 목록 조회
 */
export type getAvailableCouponsResponse200 = {
  data: AvailableCouponResponse[]
  status: 200
}
    
export type getAvailableCouponsResponseSuccess = (getAvailableCouponsResponse200) & {
  headers: Headers;
};
;

export type getAvailableCouponsResponse = (getAvailableCouponsResponseSuccess)

export const getGetAvailableCouponsUrl = () => {


  

  return `https://ticket-api.devhong.cc/api/coupons`
}

export const getAvailableCoupons = async ( options?: RequestInit): Promise<getAvailableCouponsResponse> => {
  
  return orvalFetch<getAvailableCouponsResponse>(getGetAvailableCouponsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


