/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Smarter Store API
 * Smarter Store 백엔드 API 문서

**관리자 대시보드**: [매출 현황 대시보드](/admin/dashboard.html)
 * OpenAPI spec version: 1.0.0
 */
import type {
  DailySalesResponse,
  DashboardSummaryResponse,
  GetDailySalesParams,
  GetPerformanceSalesParams,
  GetRecentBookingsParams,
  GetSummaryParams,
  PagePerformanceSalesResponse,
  PerformanceDetailSalesResponse,
  RecentBookingsResponse,
  ScheduleSalesResponse
} from '.././types';

import { orvalFetch } from '../../fetch-wrapper';

/**
 * 
            전체 매출 및 예매 현황 요약을 조회합니다.
            - 총 매출액, 예매 건수, 티켓 판매 수
            - 이전 기간 대비 변화율

            **권한: ADMIN**
        
 * @summary 대시보드 요약 조회
 */
export type getSummaryResponse200 = {
  data: DashboardSummaryResponse
  status: 200
}
    
export type getSummaryResponseSuccess = (getSummaryResponse200) & {
  headers: Headers;
};
;

export type getSummaryResponse = (getSummaryResponseSuccess)

export const getGetSummaryUrl = (params?: GetSummaryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/admin/dashboard/summary?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/admin/dashboard/summary`
}

export const getSummary = async (params?: GetSummaryParams, options?: RequestInit): Promise<getSummaryResponse> => {
  
  return orvalFetch<getSummaryResponse>(getGetSummaryUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 
            특정 회차의 상세 판매 현황을 조회합니다.
            - 총 매출, 판매/대기/가능 좌석 수
            - 등급별 판매 현황
            - 최근 예매 내역

            **권한: ADMIN**
        
 * @summary 회차별 판매 현황 조회
 */
export type getScheduleSalesResponse200 = {
  data: ScheduleSalesResponse
  status: 200
}
    
export type getScheduleSalesResponseSuccess = (getScheduleSalesResponse200) & {
  headers: Headers;
};
;

export type getScheduleSalesResponse = (getScheduleSalesResponseSuccess)

export const getGetScheduleSalesUrl = (scheduleId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/dashboard/schedules/${scheduleId}/sales`
}

export const getScheduleSales = async (scheduleId: number, options?: RequestInit): Promise<getScheduleSalesResponse> => {
  
  return orvalFetch<getScheduleSalesResponse>(getGetScheduleSalesUrl(scheduleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 
            기간별 일별 매출 추이를 조회합니다.
            - 일별 매출액, 예매 건수, 티켓 판매 수
            - 특정 공연 필터링 가능

            **권한: ADMIN**
        
 * @summary 일별 매출 추이 조회
 */
export type getDailySalesResponse200 = {
  data: DailySalesResponse
  status: 200
}
    
export type getDailySalesResponseSuccess = (getDailySalesResponse200) & {
  headers: Headers;
};
;

export type getDailySalesResponse = (getDailySalesResponseSuccess)

export const getGetDailySalesUrl = (params: GetDailySalesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/admin/dashboard/sales/daily?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/admin/dashboard/sales/daily`
}

export const getDailySales = async (params: GetDailySalesParams, options?: RequestInit): Promise<getDailySalesResponse> => {
  
  return orvalFetch<getDailySalesResponse>(getGetDailySalesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 
            공연별 매출 현황을 조회합니다.
            - 공연별 총 매출, 예매 건수, 티켓 판매 수
            - 판매율, 평균 티켓 가격

            **권한: ADMIN**
        
 * @summary 공연별 매출 목록 조회
 */
export type getPerformanceSalesResponse200 = {
  data: PagePerformanceSalesResponse
  status: 200
}
    
export type getPerformanceSalesResponseSuccess = (getPerformanceSalesResponse200) & {
  headers: Headers;
};
;

export type getPerformanceSalesResponse = (getPerformanceSalesResponseSuccess)

export const getGetPerformanceSalesUrl = (params: GetPerformanceSalesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/admin/dashboard/performances?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/admin/dashboard/performances`
}

export const getPerformanceSales = async (params: GetPerformanceSalesParams, options?: RequestInit): Promise<getPerformanceSalesResponse> => {
  
  return orvalFetch<getPerformanceSalesResponse>(getGetPerformanceSalesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 
            특정 공연의 상세 매출 현황을 조회합니다.
            - 매출 요약, 등급별 매출, 회차별 매출
            - 일별 매출 추이

            **권한: ADMIN**
        
 * @summary 공연 상세 매출 조회
 */
export type getPerformanceDetailSalesResponse200 = {
  data: PerformanceDetailSalesResponse
  status: 200
}
    
export type getPerformanceDetailSalesResponseSuccess = (getPerformanceDetailSalesResponse200) & {
  headers: Headers;
};
;

export type getPerformanceDetailSalesResponse = (getPerformanceDetailSalesResponseSuccess)

export const getGetPerformanceDetailSalesUrl = (performanceId: number,) => {


  

  return `https://ticket-api.devhong.cc/api/admin/dashboard/performances/${performanceId}`
}

export const getPerformanceDetailSales = async (performanceId: number, options?: RequestInit): Promise<getPerformanceDetailSalesResponse> => {
  
  return orvalFetch<getPerformanceDetailSalesResponse>(getGetPerformanceDetailSalesUrl(performanceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 
            최근 예매 내역을 조회합니다.
            - 예매 상태별 필터링 가능
            - 특정 공연 필터링 가능
            - 사용자 정보 마스킹 처리

            **권한: ADMIN**
        
 * @summary 최근 예매 내역 조회
 */
export type getRecentBookingsResponse200 = {
  data: RecentBookingsResponse
  status: 200
}
    
export type getRecentBookingsResponseSuccess = (getRecentBookingsResponse200) & {
  headers: Headers;
};
;

export type getRecentBookingsResponse = (getRecentBookingsResponseSuccess)

export const getGetRecentBookingsUrl = (params?: GetRecentBookingsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://ticket-api.devhong.cc/api/admin/dashboard/bookings/recent?${stringifiedParams}` : `https://ticket-api.devhong.cc/api/admin/dashboard/bookings/recent`
}

export const getRecentBookings = async (params?: GetRecentBookingsParams, options?: RequestInit): Promise<getRecentBookingsResponse> => {
  
  return orvalFetch<getRecentBookingsResponse>(getGetRecentBookingsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


